# Показатели экономической динамики

```{python}
#| layout-ncol: 2
#| column: page
#| echo: false

#import locale 
#locale.setlocale( locale.LC_ALL, 'English_United States.1252')

import plotly.express as px
import plotly.io as pio
import pandas as pd
```

В данном разделе рассмотрим объекты, которыми оперируют при анализе экономических процессов: временными рядами. Именно временными рядами являются все показатели экономической динамики, с которыми встречается экономист. Мы познакомимся с первой задачей, которую решает аналитик при работе с экономическим показателем: его декомпозицией. Мы применим алгоритмы декомпозиции к ряду выработки электроэнергии для того, чтобы идентифицировать компоненту тренда и цикла, сезонную, событийную и календарную компоненты.

Эта декомпозиция ряда позволяет разделить выделить из общего изменения в уровнях экономических индикаторов, компоненты который помогают ответить на содержательные вопросы о протекании экономических процессов (растет или снижается, ускоряется или замедляется уровень деловой активности?), от разовых всплесков и повторяющихся циклических и сезонных колебаний. 

Алгоримы декомпозиции имеют свои ограничения. Мы остановимся на проблемах отсутсвиях единственно верной декомпозиции ряда, а так же нестабильности оценок сезонной волны, просачивании влияния значительных шоков в оценки прошлой динамики.

## Временные ряды

В задачах анализа динамики объектами обработки являются временные ряды. Временным рядом ^[Cинонимы: динамический ряд, ряд динамики, хронологический ряд, time series.] называют упорядоченное множество, характеризующее изменение показателя во времени. Временные ряды традиционно обозначают $X = (x_1, x_2, ..., x_T)$, где $x_t$ - элементы такого множества или члены временного ряда. Они состоят из численных значений показателя $x_t$, называемых уровнями временного ряда, и периодов $t$, к которым относятся уровни. При работе с временными рядами время считается дискретным.

Под периодами понимаются моменты или интервалы времени - и в зависимости от того, является ли индекс времени моментом или интервалом различают моментные и интервальные временные ряды. 

Если уровни временного ряда отражают значение показателя на моменты времени, то такие переменные называют переменными типа запаса^[англ. stock variables] или моментными временными рядами. Если уровни временного ряда отражают значение показателя за период, то такие временные ряды называют интервальными или переменными типа потока^[англ. flow variables]. 

Примерами переменных типа запаса, которым соответствуют моментные временные ряды, являются масса объекта, температура больного, заряд конденсатора, обменный курс рубля к доллару, численность занятых в экономике, объем денежной массы, ставка процента, цена товара или услуги. Два примера переменных типа запаса приведены на @fig-ch_econ_dyn_econts_moment. Здесь и индекс денежной массы на @fig-ch_econ_dyn_econts_moment-1, и индекс потребительских на @fig-ch_econ_dyn_econts_moment-2 цен отражают уровень экономической переменной на заданный момент времени.

:::  {layout-ncol=2 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_moment
#| fig-cap: "Примеры моментных экономических временных рядов"
#| fig-subcap:
#|   - "Индекс денежной массы М2"
#|   - "Индекс потребительских цен"
#| layout-ncol: 2
#| column: page
#| echo: false

ts_m2 = pd.read_excel(r'./data/m2_m.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     ['M2'] \
     .resample('M').last() \
     .pipe(lambda ts: ts.div(ts.iloc[0]))
fig = px.line(ts_m2).update_layout(
     yaxis_title="Индекс (12М2001 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()

ts_cpi_m = pd.read_excel(r'./data/cpi_m.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     ['MM'] \
     .dropna() \
     .resample('M').last() \
     .div(100).add(1).cumprod() \
     .pipe(lambda ts: ts.div(ts.iloc[0]))
fig = px.line(ts_cpi_m).update_layout(
     yaxis_title="Индекс (12М1996 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()
```
:::

Если временной индекс отражает интервал времени, то временной ряд является рядом типа потока. К примерам интервальных рядов относят рассеиваемую мощность, расход реагентов в химическом реакторе, валовой внутренний продукт, объем экспорта, розничный товарооборот. На @fig-ch_econ_dyn_econts_int приведены два примера интервальных временных рядов: производство электроэнергии на @fig-ch_econ_dyn_econts_int-1 (ряд, с которым мы близко познакомимся в этой главе) и индекс реальных доходов населения на @fig-ch_econ_dyn_econts_int-2. В обоих случаях индикаторы демонстрируют интенсивность явления за заданный период времени.

::: {layout-ncol=2 .column-page}

```{python}
#| label: fig-ch_econ_dyn_econts_int
#| fig-cap: "Примеры интервальных экономических временных рядов"
#| fig-subcap:
#|   - "Производство электроэнергии"
#|   - "Индекс реальных располагаемых денежных доходов населения"
#| layout-ncol: 2
#| column: page
#| echo: false

df_ee = pd.read_excel(r'./data/electricitygeneration.xlsx'
     , sheet_name='X'
     , index_col='ds'
     , skiprows= range(1,5)) \
     [['Electricity Generation']] \
     .resample('M').last()
fig = px.line(df_ee).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()


ts_hhi_q = pd.read_excel(r'./data/hhi_q.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     ['QQ'] \
     .dropna() \
     .resample('Q').last() \
     .div(100).add(1).cumprod()
fig = px.line(ts_hhi_q).update_layout(
     yaxis_title="Индекс (4кв1998 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()

```
:::

Кроме типа временные ряды различают еще по двум признакам: регулярность ряда и полнота регистрации значений ряда.

Различают временные ряды с равноотстоящими уровнями, которые получаются путем регистрации данных через промежутки времени одинаковой продолжительности^[Равным шагом по времени], и временные ряды с неравноотстоящими уровнями. Временные ряды с равноотстоящими уровнями можно также называть временными рядами с постоянным шагом по времени. Таким шагом может быть неделя, месяц, квартал или год для большинства экономических рядов. Постоянство шага по времени позволяет говорить о частоте временного ряда - чем меньше шаг по времени, тем выше частота ряда.

Следует отметить, что регулярность экономических рядов условна. Хотя принято считать месячные индикаторы промышленного производства или потребительских цен регулярными, в физическом смысле это не верно. Например, количество дней в месяцах различно и варьируется от 28 до 31 дня, что приводит к тому, что длина периодов варьируется. Наличие високосных лет приводит к тому, что и годовые данные не строго регулярны. Тем не менее, методы календарной и сезонной коррекции позволяют отчасти устранить такие эффекты. 

Различают полные и неполные временные ряды. У неполного временного ряда для некоторых периодов отсутствуют значения. Если же все значения ряда доступны, то его называют полным. Следует отметить, что между неполными рядами и рядами с неравноотстоящими уровнями нет четкой границы. Так, пропуск регистрации одного значения временного ряда приведет к его переходу из категории полных рядов с постоянным шагом, в категорию неполных рядов с неравноотстоящими уровнями, поскольку расстояние между значениями в окрестности пропущенного окажется вдвое больше нормы для этого ряда.

::: {.callout-tip collapse="false" title="Регулярный, нерегулярный или неполный?"}

Иллюстрацией нечеткой границы между неполными и нерегулярными рядами дает опыт оценки инфляционных ожиданий потребителей Банком России и ФОМ.  Банк России [публикует](https://cbr.ru/statistics/ddkp/inflationary_expectations/) оценки ежемесячных инфляционных ожиданий потребителей на основе опросов ФОМ. Замеры инфляционных ожиданий осуществляются на основе регулярных, ежемесячных «face-to-face» опросов, и ряд этих оценок разрабатывался как регулярный и полный.

Однако, в 2020 г. распространение вируса COVID-19 и риски заражения как интервьюеров, так и респондентов сделали невозможным опросы в прежнем формате в течении ряда месяцев. Волны опроса с апреля по июнь 2020 г. ФОМ проводил в виде телефонных интервью респондентов. Новый метод измерения ожиданий отличался от стандартног, а следовательно полученные таким образом данные, [согласно ФОМ](https://cbr.ru/Collection/Collection/File/27861/inFOM_20-04_2.pdf), "не могут быть напрямую сопоставлены с данными предыдущих исследований". 

Таким образом, временной ряд оценок инфляционных ожиданий потребителей стал неполным и нерегулярным. Нерегулярность данных вносит дополнительные сложности в анализ как инфляционных ожиданий, так и их связи с другими индикаторами. Аналитики должны будут адаптировать стандартные методы анализа временных рядов, которые предназначены для работы с полными рядами с постоянным шагом.
:::

## Экономические временные ряды

Выше речь шла о временных рядах вообще, безотносительно к предметной области. Ниже мы сосредоточимся на экономических временных рядах^[Синонимы: временные ряды экономических показателей, economic time series], которые являеются предметом внимания исследований экономической динамики. 

Перед тем, как перейти к обсуждению особенностей экономический временных рядов отметим, что здесь и ниже, если это специально не оговорено, все данные относятся к российской экономике. Кроме того, числа, указанные вдоль оси времени на графиках временных рядов в месячном и квартальном выражении, соответствуют дню окончания периода: значение соответствующее январю приходится на 31 число, первому кварталу - 31 марта, году - 31 декабря. Наконец, показателями в реальном выражении называем такие показатели, на динамику которых не оказывает непосредственного влияния изменение цен.

Экономические временные ряды обладают определенной спецификой, которая отличает их от временных рядов общего вида, в частности от временных рядов, встречающихся в естествознании и в технических приложениях. Эта специфика порождает отличия методов их анализа от методов анализа временных рядов общего вида, подобно тому, как существенность порядка порождает отличия методов анализа временных рядов от методов анализа неупорядоченных совокупностей. Среди общих закономерностей динамики экономических рядов следует выделить две. 

Во-первых, индикаторы цен обычно более подвижны, чем индикаторы количеств. Например, на графике @fig-ch_econ_dyn_econts_pricevsvol_vol-1 видно, что индекс промышленного производства в обрабатывающей промышленности менялся значительно плавнее, чем индекс цен производителей на @fig-ch_econ_dyn_econts_pricevsvol_vol-2 в этой сфере. За сравнимый период с января 1999 г. индекс количества выпуска вырос менее, чем в 3 раза, тогда года как индекс индекс вырос более чем в 20 раз. Индексы цен являются одними из самых волатильных временных рядов: валютные курсы, индексы цен акций и облигаций. Волатильность индексов количеств заметно ниже: количество занятых в экономике, оборот розничной торговли или объем добычи нефти меняются значительно плавнее. 

:::  {layout-ncol=2 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_pricevsvol_vol
#| fig-cap: "Пример динамики индикаторов объемов и цен"
#| fig-subcap:
#|   - "Индекс промышленного производства"
#|   - "Индекс цен производителей"
#| layout-ncol: 2
#| column: page
#| echo: false

ts_ip_ix = pd.read_excel(r'./data/ipx_m.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     ['MM'] \
     .resample('M').last() \
     .loc['1999-01':] \
     .div(100).add(1).cumprod() \
     .pipe(lambda ts: ts.div(ts.iloc[0]))
fig = px.line(ts_ip_ix).update_layout(
     yaxis_title="Индекс (01М1999 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()

ts_ppi_ix = pd.read_excel(r'./data/ppi_m.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     ['MM'] \
     .resample('M').last() \
     .loc['1999-01':] \
     .div(100).add(1).cumprod() \
     .pipe(lambda ts: ts.div(ts.iloc[0]))
fig = px.line(ts_ppi_ix).update_layout(
     yaxis_title="Индекс (01М1999 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()
```
:::

Во-вторых, многие экономические ряды имеют выраженную регулярную сезонность. На @fig-ch_econ_dyn_econts_retail_sales_nsavssa приведена иллюстрация динамики объемов розничной торговли. Из иллюстрации видно, что значительные сезонные колебания временного ряда могут скрыть изменения в уровне активности. Ниже мы познакомимся с методами коррекции сезонности и декомпозицией экономических временных рядов на компоненты.

```{python}

#| label: fig-ch_econ_dyn_econts_retail_sales_nsavssa
#| fig-cap: "Индекс оборта розничной торговли"
#| layout-ncol: 1
#| column: page
#| echo: false


# проведена сезонная корректировка
# Исходный индекс

ts_rs_ix = pd.read_excel(r'./data/rs_m.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     ['MM'] \
     .resample('M').last() \
     .loc['1995-01':] \
     .div(100).add(1).cumprod() \
     .pipe(lambda ts: ts.div(ts.iloc[0]))

fig = px.line(ts_ppi_ix).update_layout(
     yaxis_title="Индекс (01М1999 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()
```

### Динамическая структура экономических временных рядов

Экономические временные ряды, как и временные ряды во многих других областях, можно рассматривать в виде совокупности составляющих динамики, т.е. как функцию (например, произведение или сумму) нескольких временных рядов. Таким образом, наблюдаемый экономический временной ряд предполагается состоящим из ненаблюдаемых составляющих динамики. Изменения уровней различных составляющих динамики обычно определяются разными группами причин, поэтому составляющие часто можно в первом приближении рассматривать как независимые. 

В составе экономических временных рядов часто выделяют компоненту тренда, циклические составляющие разной продолжительности, сезонную и нерегулярную составляющую. Совокупность трендовой и циклических составляющих называют компонентой тренда и конъюнктуры или просто трендовой составляющей^[англ. trend-cycle component]. Помимо этого, экономические временные ряды более высокой, чем годовая, частоты обычно содержат календарную и сезонную составляющие. Таким образом, экономические временные ряды обладают специфической динамической структурой. 

Для решения многих задач анализа экономической динамики бывает необходимо выделять некоторые составляющие динамики из их совокупности, т.е. проводить операцию декомпозиции (разложения) экономических временных рядов на составляющие динамики. Такая операция декомпозиции является частным случае принципа редукционизма: попытки разложить сложное явление на более простые составные части. 

В случае временных рядов принцип редукционизма предлагает рассматривать сложную динамику временного ряда как сумму компонент, поведение каждой из которых задается различными механизмами. Скажем, компонента тренда розничных продаж может быть связана с изменениями в доступности кредитования и уровнем уверенности потребителей, а сезонная компонента - годовым циклом отпусков и праздников. Аналогом редукционизма является разложение ряда в ряд Фурье в области анализа сигналов, который используется и в области идентификации циклов в экономических рядах.

Ниже мы познакомимся с каждой из четырех основных компонент экономических временных рядов по очереди: календарной, сезонной, нерегулярной и компонентой тренда и конъюнктуры. В качестве нашего объекта исследования будем использовать ряд ежемесячной выработки электроэнергии. Этот ряд привлекателен тем, что одновременно представляет интерес для аналитика как оперативный индикатор деловой активности, однако идентификациия содержательных изменений требует удаления выраженной сезонной и календарной компонент.

Для того, чтобы начать работу с рядом, получим его значения из подготовленного файла или из первичного источника [ЕМИСС](https://fedstat.ru/indicator/57783).

```{python}
#| echo: true

df_ee = pd.read_excel(r'./data/electricitygeneration.xlsx'
     , sheet_name='X'
     , index_col='ds'
     , skiprows= range(1,5)) \
     [['Electricity Generation']] \
     .resample('M').last()
```

На @fig-ch_econ_dyn_econts_electricitygen отражена динамика выработки электроэнергии. Видно, что без коррекции выраженной сезонной волны и календарных эффектов, для экономиста будет затруднительно идентификацировать точек иземенения тренда в уровнях выработки. 

```{python}
#| label: fig-ch_econ_dyn_econts_electricitygen
#| fig-cap: "Выработка электроэнергии"

fig = px.line(df_ee).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()
```

### Календарная составляющая динамики

Календарная составляющая^[англ. calendar component, calendar variations] обусловлена различием числа рабочих дней в разных месяцах или кварталах и различиями протекания экономических процессов в разные дни недели, праздники, предпраздничные дни. Так, календарные месяцы содержат разное число дней (в феврале високосного года 29 дней, в обычные годы  28, остальные месяцы содержат 30 или 31 день). Поэтому временные ряды месячных, квартальных и даже годовых данных, строго говоря, являются временными рядами с неравноотстоящими уровнями.

Но это не единственная причина возникновения календарной составляющей динамики. Даже если бы все месяцы состояли из одинакового числа дней, то и в этом случае многие экономические временные ряды содержали бы заметную календарную составляющую динамики в силу трех причин. 

Во-первых, число выходных дней изменяется от месяца к месяцу и для одного месяца в различные годы из-за различного числа выходных и рабочих дней. Это происходит по следующией причине. Количество дней в невисокосном году в 365 делятся на цело на 7 с остатком 1. Это первый день недели начала следующего года сдвинут на 1 относительно текущего для невисокосных лет, что делает различным чило выходных и рабочих дней для одинаковых месяцев различных лет.

Во-вторых, праздничные дни по-разному распределены по различным месяцам. Некоторые праздники (например, Пасха) в разные годы могут приходиться на разные месяцы.

В-третьих, различные дни недели неравнозначны в смысле протекания экономических процессов. Начало и конец рабочей недели обычно менее эффективны, чем ее середина. Также замечено, что в предпраздничные и послепраздничные дни эффективность работы зачастую снижается. Поэтому, хотя различия в продолжительности календарных месяцев, конечно, играют большую роль при формировании календарной составляющей динамики экономических временных рядов, другие факторы также способны вносить в нее значительный вклад. 

Календарные эффекты у разных временных рядов выражены в разной степени. У интервальных временных рядов календарные эффекты выражены гораздо сильнее, чем у моментных. Причиной является то, что уровни интервального временного ряда в первом приближении пропорциональны продолжительности шага по времени (так, добыча нефти за квартал в первом приближении в три раза выше, чем за месяц). Уровни же моментного временного ряда, напротив, гораздо слабее зависят от продолжительности шага по времени. 

В первом приближении пропорциональны продолжительности шага по времени лишь первые разности моментного временного ряда (так, изменение цены некоторого товара за год будет на порядок больше, чем за месяц). Учитывая то, что изменения моментных экономических временных рядов за месяц, как правило, не превышают единиц процентов, получаем, что календарный фактор для моментных временных рядов выражен на полтора-два порядка слабее, чем для интервальных. 

Как правило, чем меньше шаг по времени, тем сильнее выражены календарные эффекты. Причина этого состоит в том, что по мере укрупнения шага по времени различия в числе и календарных, и рабочих дней в относительном выражении уменьшаются. Так, число рабочих дней в календарном месяце (т. е. число дней в месяце за вычетом числа суббот, воскресений и праздников) может изменяться от 18 до 23, т. е. максимальное число рабочих дней превышает минимальное на 28%, тогда как число рабочих дней в разные годы может изменяться от 250 до 255, при этом максимальное число рабочих дней превышает минимальное всего на 2%. Поэтому масштаб календарной составляющей годовых рядов в относительном выражении на порядок меньше, чем для рядов помесячной динамики. 

Иллюстрацию зависимости масштаба календарных эффектов от величины шага по времени дает рис. @fig-ch_econ_dyn_econts_crude c помесячной и поквартальной динамикой добычи нефти. Нефть добывают непрерывно в течение всего года, днем и ночью, зимой и летом. Среднесуточные объемы добычи нефти слабо подвержены воздействию сезонных и случайных факторов, их динамика обладает высокой инерционностью, что обусловлено особенностями технологии. Поэтому объем добычи нефти за месяц в первом приближении пропорционален продолжительности месяца. Это хорошо на месячном графике @fig-ch_econ_dyn_econts_crude, где в феврале каждого года наблюдается резкое снижение объемов добычи (причем в високосные годы это снижение бывает менее резким), а объемы добычи нефти в месяцы, содержащие 31 день, примерно на 3% превышают объемы добычи соседних месяцев, содержащих 30 дней. Если на основе этого временного ряда получить ряд в квартальном выражении, то масштаб календарных эффектов в относительном выражении резко снизится. 

```{python}
#| label: fig-ch_econ_dyn_econts_crude
#| fig-cap: "Добыча нефти"

df_crude = pd.read_excel(r'./data/crude_m.xlsx'
     , sheet_name='X'
     , index_col='ds'
     , skiprows= range(1,5)) \
     [['Crude oil, k ton']] \
     .resample('M').last()\
     .assign(**{
          '3MMA': lambda df: df['Crude oil, k ton'].rolling(3).mean()
          })


fig = px.line(df_crude).update_layout(
     yaxis_title="тыс. тон"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()
```

Заметим, что использованный в данном примере временной ряд добычи нефти не вполне типичен, поскольку изменения его уровней от месяца к месяцу определяются в основном календарной составляющей, тогда как остальные составляющие динамики либо крайне слабо выражены (сезонная и нерегулярная), либо изменяются очень плавно (компонента тренда и конъюнктуры). Чаще бывает, что календарная составляющая не доминирует, а лишь привносит характерные высокочастотные флуктуации в динамику показателя, накладываясь на прочие составляющие. 

Таким образом, динамика экономических временных рядов зачастую заметно различается в зависимости от их частоты и от того, являются ли они моментными или интервальными рядами. Это хорошо видно при сопоставлении графиков интервальных временных рядов на @fig-ch_econ_dyn_econts_int с графиками моментных рядов на @fig-ch_econ_dyn_econts_moment. Различия динамики моментных и интервальных временных рядов проявляются, главным образом, у рядов с шагом по времени менее года, тогда как интервальные и моментные ряды годовой динамики демонстрируют меньше различий. Из этого правила, есть исключения. Например, для некоторых рядов годовой частоты имеет смысл корректировать на календарность в окрестности високосных лет. Например, для отраслей с пятидневной рабочей неделей в году обычно около 248 рабочих дней, следовательно 1 дополнительный рабочий день может добавить 0.4% рабочего времени, что может заметно повлиять на уровни интервальных временных рядов.

Поэтому, хотя календарную составляющую динамики могут содержать, вообще говоря, как интервальные, так и моментные экономические временные ряды с любым шагом по времени (месячные, квартальные, годовые), ее учитывают обычно лишь у интервальных временных рядов с шагом по времени менее года. Другие экономические временные ряды с хорошей точностью можно считать не содержащими календарной составляющей.

::: {.callout-tip collapse="false" title="Эффект Пасхи"}

Из этого правила есть исключения. Вероятно наиболее яркий пример необходимости корректировать календарные эффекты у моментного индекса является эффект Пасхи на индексы цен продовольствия. В предверии пасхи статистика регулярно фиксирует рост цен на куриные яйца и иные виды продовольствия, и снижение впоследствие. Пасха относится к праздникам, которые могут приходиться на разные месяцы в различные годы, поэтому этот эффект относят к [календарным](https://www.ecb.europa.eu/pub/pdf/other/mb201405_focus04.en.pdf), а не сезонным.

:::

Наличие календарной составляющей приводит к тому, что уровни экономических временных рядов могут быть не вполне сопоставимыми между собой, а это может приводить к неадекватной содержательной интерпретации экономической динамики, снижению точности прогнозов, неверной идентификации связей. Для устранения этого источника несопоставимости календарную составляющую динамики необходимо идентифицировать и устранить. 

При декомпозиции экономического временного ряда на составляющие динамики календарную составляющую обычно идентифицируют и удаляют в первую очередь. Процедуру элиминирования календарной составляющей динамики называют календарной корректировкой^[англ. calendar adjustment]. Временные ряды, полученные из исходных в результате проведения этой процедуры, называют календарно скорректированными^[англ. calendar adjusted]. Календарно скорректированный ряд содержит три из четырех составляющих динамики исходного временного ряда: сезонную, нерегулярную и компоненту тренда и конъюнктуры. 

Обычно календарную составляющую считают мультипликативной. Пусть $t$ - время, а $x_t$,  $C_t$, $S_t$,  $I_t$ и $T_t$ - уровни исходного ряда и его календарной, сезонной, нерегулярной и тренда и конъюнктуры $T_t$ составляющих периода $t$ соответственно, тогда исходный ряд представляют в виде:

$$
x_t = C_t \cdot F(T_t,S_t,I_t)
$$

Динамическую структуру типичного экономического временного ряда рассмотрим на примере ряда ежемесячного производства электроэнергии в России, график которого приведен на @fig-ch_econ_dyn_econts_int. На @fig-ch_econ_dyn_econts_electricity_calendar_comp показана одна из возможных оценок его календарной составляющей динамики и исходный ряд с элиминированной календарной составляющей. Произведение двух рядов, приведенных на @fig-ch_econ_dyn_econts_electricity_calendar_comp, дает исходный ряд производства электроэнергии, график которого приведен на @fig-ch_econ_dyn_econts_int.

Существует большое количество методов календарной корректировки. Простейший из них основан на использовании априорной информации о характере календарных флуктуаций и состоит в делении уровней интервальных временных рядов на коэффициенты пересчета, пропорциональные количеству рабочих дней в соответствующем месяце или квартале. Совокупность таких коэффициентов пересчета и образует оценку календарной составляющей, единую для целого класса временных рядов. Такая корректировка не подходит для моментных временных рядов, для которых требуется корректировать темпы прироста, а не уровни ряда.

Проведем простейшую календарную корректировку для ряда производства электроэнергии. Для этого сначала найдем среднее число дней в календарном месяце - именно к таком "нормальному" месяцу мы приведем ряд в результате корректировки. 

```{python}
mean_month_length = df_ee.index.day.to_numpy().mean()
mean_month_length
```

Зная число дней в "нормальном" месяце, мы можем оценить корректировочные коэффициенты для каждого из месяцев нашего ряда. Для этого разделим фактическое число дней в месяце на число дней в "нормальном" месяце.

```{python}
wd_corr = df_ee.index.day.to_numpy()/(mean_month_length)

```

Наконец, мы применим корректировочные коэффициенты к исходному ряду выработки электроэнергии. Например, мартовские значения, т.е. значения для месяца длительностью в 31 день будут скорректированные вниз делением на $31/30.433 \approx 1.01863$, тогда как значения выработки для невисокосного февраля будут скорректированны вверх делением на $28/30.433 \approx 0.920054$.

```{python}
df_ee['Electricity Generation, CA'] = df_ee['Electricity Generation'].div(wd_corr)

```

Оценки корректировочных коэффициентов приведены на @fig-ch_econ_dyn_econts_electricity_calendar_comp-1, тогда как исходный и скорректированный на календарность ряды выработки электроэнергии приведены на @fig-ch_econ_dyn_econts_electricity_calendar_comp-2.

:::  {layout-ncol=2 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_electricity_calendar_comp
#| fig-cap: "Производства электроэнергии"
#| fig-subcap:
#|   - "Корректирующий календарный коэффициент"
#|   - "Ряд с коррекцией на каледнарность"
#| layout-ncol: 2
#| column: page
#| echo: true

fig = px.line(pd.Series(wd_corr,index=df_ee.index)) \
     .update_layout(
     yaxis_title="Mean Month = 1.0"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()

fig = px.line(df_ee[['Electricity Generation','Electricity Generation, CA']]).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"
     ))
fig.show()
```

:::

Для некоторых экономических процессов рабочими днями являются все дни недели. Такие процессы называют непрерывными или семидневными. К их числу, среди прочих, относятся добыча нефти и производство электроэнергии. Для других экономических процессов рабочими днями являются дни недели с понедельника по пятницу за вычетом праздников. Такие процессы называют пятидневными. Реже встречаются процессы с другим числом рабочих дней, скажем, шестидневные. При таком подходе идентификация календарной составляющей динамики сводится к определению принадлежности данного процесса к одному из типов процессов (пятидневные процессы, непрерывные и т. п.), что обычно осуществляется экспертным путем.

Простейшие методы нормировки числа рабочих дней в периоде учитывают лишь различия в числе рабочих дней, но не учитывают различий в протекании экономических процессов в разные дни недели, предпраздничные и послепраздничные дни, о которых говорилось выше. Учесть эти различия позволяют более совершенные методы календарной корректировки, в которых календарная составляющая динамики не задается априорно для всех временных рядов некоторого класса, а оценивается на данных. С этой целью для каждого корректируемого временного ряда строят регрессионные модели, в которых в качестве независимых переменных используют временные ряды, уровни которых равны числу дней недели данного типа в месяце (ряды числа понедельников в месяце, вторников и т.д.), и аналогичные ряды для учитываемых праздников (см., например, [@findley1998new; @eurostatsahandbook2018; @Shiskin1967]). 

При использовании примитивных методов календарной корректировки неудаленный остаток календарной составляющей отчасти попадет (просочится) в оценку сезонной составляющей и может быть исключен вместе с ней, а отчасти попадет в оценку нерегулярной составляющей динамики, что снизит точность идентификации компоненты тренда и конъюнктуры. 

Следует отметить, что не всегда возможно однозначно идентифицировать рабочие и праздничные дни. Так, возникают ситуации неопределенности. Например, [день парада Победы 24.06.2020](https://www.rbc.ru/society/29/05/2020/5ed1466e9a79478b8ab15ea3) был объявлен нерабочим днем - типом дня, который не относится ни к рабочим дням, ни к праздничным. Аналогичный промежуточный статус имели день голосования по Конституции 01.07.2020, каникулы 04–07.05.2021.

### Сезонная составляющая динамики

Благодаря наличию сезонной составляющей динамики^[англ. seasonal component, seasonal variations] уровни временного ряда, соответствующие определенным месяцам или кварталам, регулярно бывают выше или ниже уровней других месяцев или кварталов. Сезонные колебания бывают обусловлены регулярно изменяющимися погодно-климатическими условиями, ритмичностью производственных процессов (сдача жилья в эксплуатацию в конце года, годовое бюджетное финансирование, выплата премий по итогам года и к праздникам), ритмичностью учебного процесса, периодами предпраздничной торговли, периодами массовых отпусков и другими подобными причинами. 

Различают цикличность и периодичность. Под цикличностью понимается повторяемость явления в общих чертах. Периодичность является частным случаем цикличности, когда картина повторяется в деталях на каждом следующем цикле. Сезонные колебания дают пример цикличности, но, вообще говоря, не периодичности, поскольку, несмотря на повторяемость в общих чертах, они очень часто демонстрируют эволюцию со временем как масштаба, так и формы. Заметим, что сезонные колебания являются весьма специфичным частным случаем цикличности, когда продолжительность цикла можно считать постоянной. Эта специфика существенно используется при идентификации сезонной составляющей. Соответствующие методы значительно отличаются от методов идентификации циклов общего вида, которые применяются, например, при анализе циклов деловой активности. 

Сезонную составляющую, по определению, могут содержать только временные ряды с шагом по времени меньше года (полугодовые, квартальные, месячные и т. д.). Смысл проведения сезонной корректировки – придать уровням временного ряда сопоставимость в пределах года, т.е. удалить сезонную составляющую и только ее.  

Сезонные эффекты, как и календарные, у разных временных рядов выражены в разной степени. У многих временных рядов амплитуда сезонных колебаний может быть весьма значительна (например, индексы реальных располагаемых доходов на @fig-ch_econ_dyn_econts_int-2), тогда как у некоторых временных рядов сезонные колебания могут практически отсутствовать (как у добычи нефти на @fig-ch_econ_dyn_econts_crude).

Интервальные временные ряды, как правило, в большей мере, чем моментные, подвержены влиянию сезонного фактора. Это обусловлено соотношениями между переменными типа запаса и типа потока и, соответственно, между моментными и интервальными экономическими временными рядами. Так, временной ряд, сформированный из первых разностей уровней моментного ряда, является интервальным, а временной ряд, сформированный из сумм нарастающим итогом всех членов интервального ряда, начиная с некоторого фиксированного периода по текущий, является моментным. Таким образом, соотношение между моментными и интервальными рядами подобно соотношению между функциями и их производными. Изменения с течением времени (в том числе и сезонные) многих переменных типа запаса реализуются в экономике через их приросты (скажем, объем денежной массы изменяется вследствие роста кредитования), т.е. через переменные типа потока, суммирование которых нарастающим итогом уменьшает масштаб сезонной составляющей (как и календарной) в относительном выражении.

Наличие сезонной составляющей динамики часто приводит к несопоставимости между собой уровней экономических временных рядов. Так, с августа 2020 г. помесячные темпы выработки электроэнергии в натуральном выражении показывали значительный рост по сравнению с предыдущими месяцами. Этот рост возможно было объяснить восстановление деловой активности после постепенного снятия ограничений из эпидемии COVID-19. С другой стороны подобный рост, обусловленный сезонными причинами, наблюдался ежегодно - как до 2020 г., так и позднее. Если задача анализа состоит в том, чтобы оценить тенденции в производстве электроэнергии связанные с изменение деловой активности, то сезонная составляющая динамики не несет полезной информации для ее решения, а лишь порождает несопоставимость между уровнями, соответствующими разным календарным месяцам. Поэтому для решения такой задачи сезонную составляющую, как и календарную, необходимо элиминировать, чтобы обеспечить сопоставимость между уровнями временного ряда. 

Заметим, что хотя для многих задач анализа экономической динамики сезонная составляющая не является информативной и поэтому должна быть элиминирована, существуют задачи, в которых сезонная составляющая является информативной. Так, планирование поставок товаров в торговую сеть осуществляется в соответствии с ожидаемой динамикой спроса и в данном случае сезонная составляющая (как и календарная) несет важную информацию. Таким образом, наличие сезонной составляющей не всегда приводит к несопоставимости уровней временных рядов и вопрос о необходимости ее удаления должен решаться в каждом конкретном случае в зависимости от задачи исследования. 

Процедуру элиминирования сезонной составляющей динамики называют сезонной корректировкой^[англ. seasonal adjustment]. Временные ряды, полученные в результате проведения этой процедуры, называют сезонно скорректированными ^[англ. seasonally adjusted]. Обычно сезонной корректировке подвергают ряды, предварительно уже очищенные от влияния календарного фактора, т. е. календарно скорректированные временные ряды. Поэтому под сезонно скорректированными рядами обычно понимают ряды, в необходимых случаях предварительно подвергнутые также и календарной корректировке. Таким образом, если исходный временной ряд рассматривается как совокупность календарной, сезонной, нерегулярной и трендовой составляющих динамики, то сезонно скорректированный ряд включает трендовую и нерегулярную составляющие динамики исходного временного ряда. 

::: {.callout-caution collapse="false" title="Коррекция, не сглаживание"}

Распространен неудачный термин – "сезонное сглаживание". Для обозначения процедуры сезонной корректировки в последние годы в России получил распространение термин "сезонное сглаживание", который неудачен, по крайней мере, по двум причинам. 

Во-первых, понятие "сглаживание" неявно подразумевает получение гладкого результирующего временного ряда, тогда как результат сезонной корректировки вовсе не обязан быть гладким хотя бы потому, что в состав сезонно скорректированного ряда входит нерегулярная составляющая динамики, а компонента тренда и конъюнктуры может претерпевать скачки и изломы. 

Во-вторых, возникает представление о методах сезонной корректировки как о разновидности методов сглаживания, тогда как они отличаются по существу: сглаживание состоит в удалении высокочастотной составляющей, тогда как сезонная корректировка состоит в удалении сезонной составляющей без удаления высокочастотных составляющих, не являющихся гармониками сезонной составляющей.
:::

Для идентификации сезонной составляющей из совокупности сезонной, нерегулярной и трендовой составляющих необходимо привлечение дополнительной информации о виде функции $F(\cdot)$ и о свойствах составляющих динамики. В большинстве случаев полагают, что сезонный эффект представлен мультипликативно или аддитивно:

$$
F(T_t,S_t,I_t)=T_t \cdot S_t \cdot I_t
$$

$$
F(T_t,S_t,I_t)=T_t+S_t+I_t
$$

Эти два типа моделей сезонности являются простейшими. Обычно отдают предпочтение тому представлению (мультипликативному или аддитивному), в котором сезонная волна демонстрирует наименьшую эволюцию, т.е. более стабильна. Чаще используется мультипликативное представление. Иногда применимо лишь аддитивное представление (например, когда исходный ряд – знакопеременный).

Сезонные эффекты, несмотря на то что время их наступления и характер год от года могут несколько изменяться, имеют достаточно регулярный, повторяющийся в общих чертах характер, которого другие компоненты временного ряда (за исключением календарной составляющей), как правило, не имеют. Повторяемость сезонных колебаний и позволяет проводить идентификацию сезонной составляющей. 

Проведение сезонной корректировки базируется на наличии двух видов близости (связности) между членами временного ряда: связности между соседними членами ряда и близости между членами ряда, соответствующими одинаковым месяцам (кварталам) соседних лет. Последний вид связности присущ только сезонной составляющей, тогда как компонента тренда и конъюнктуры и нерегулярная составляющая им не обладают. 

Хотя временной ряд числа рабочих дней в различные месяцы содержит очевидную сезонную волну, которая может быть устранена сезонной корректировкой, проведение сначала календарной корректировки способно заметно улучшить качество результата последующей сезонной корректировки. Другими словами, календарная корректировка не может быть сведена к сезонной, несмотря на наличие значительной сезонной волны в составе календарной составляющей динамики.

Сезонность – это нетривиальное явление, в отличие от календарности. Сезонные колебания являются примером цикличности (повторяемость в общих чертах), но, вообще говоря, не периодичности (повторяемость в деталях). Сезонные колебания часто демонстрируют эволюцию масштаба и формы. В следующем разделе мы кратко познакомимся с историей методов декомпозиции экономических временных рядов.


Начнем, с практического примера сезонной корреции ряда выработки электроэнергии. Для коррекции мы выибираем алгортим [X-13ARIMA-SEATS](https://www.census.gov/data/software/x13as.html), который является стандартом в области сезонной корректировки. Умение использовать этот алгоритм позволит аналитику воспроизвести оценки сезонно-скорректированной [инфляции Банка России](https://www.cbr.ru/statistics/ddkp/aipd/), что может быть полезно для текущего анализа инфляционной картины. Выбранный нами алгоритм не является единственным и мы предлагаем историческую справку о развитии и разнообразии методов сезонной коррекции в @tip-historysa.

```{python}
from statsmodels.tsa.x13 import x13_arima_analysis

# Каталог с программой https://www.census.gov/data/software/x13as.html
fd_x13 = r'./x13as/'

```

В настоящем примере мы полагаемся на стандартные параметры алгоритма X13 в поиске модели временного ряда и выбора сезонности для выработки электро энергии. На правктике, подбор модели временного ряда и параметров сезонной корректировки может занимать большое пространство в работе аналитика. 

```{python}

x13_res = x13_arima_analysis(df_ee['Electricity Generation, CA']
     , log=True
     , x12path=fd_x13)

df_ee['Electricity Generation, SWDA'] = x13_res.seasadj

```

Полученная оценка сезонно скорректированного ряда позволяет нам оценить коэффициенты сезонной корректировки. Они равны отношению нескорректированного на сезонность ряда к скорректированному.

```{python}

df_ee['Electricity Generation, SF'] = df_ee['Electricity Generation, CA'].div(df_ee['Electricity Generation, SWDA'])

```

Наконец, не @fig-ch_econ_dyn_econts_electricity_seasonal_comp приведена оценка сезонной составляющей временного ряда производства электроэнергии и этот же ряд с элиминированными календарной и сезонной составляющими. Произведение двух рядов, приведенных на @fig-ch_econ_dyn_econts_electricity_seasonal_comp, дает ряд, график которого представлен на @fig-ch_econ_dyn_econts_electricity_calendar_comp. 

Сделаем два наблюдения. Во-первых, видим на @fig-ch_econ_dyn_econts_electricity_seasonal_comp-2, что после удаления календарной и сезонной составляющих динамика этого ряда не содержит явно выраженных циклических составляющих со средней продолжительностью циклов, не превышающей одного года (ср. @fig-ch_econ_dyn_econts_int и  @fig-ch_econ_dyn_econts_electricity_seasonal_comp). Во-вторых, на @fig-ch_econ_dyn_econts_electricity_seasonal_comp-1 видим, что сезонная составляющая демонстрирует плавную эволюцию со временем масштаба и формы сезонных колебаний. Видно, что их амплитуда несколь сужалась между 2015 и 2020 гг. по отношению с началом периода наблюдения, но возрасла с 2022 года. У таких измениях в амплитуде сезонных колебаний часто есть содержательные объяснения, которые связаны с изменением природы спроса и предложения.

:::  {layout-ncol=2 .column-page}
```{python}

#| label: fig-ch_econ_dyn_econts_electricity_seasonal_comp
#| fig-cap: "Производство электроэнергии"
#| fig-subcap:
#|   - Оценка сезонных коэффициентов
#|   - Ряд с исключением сезонности и календарного фактора"
#| layout-ncol: 2
#| column: page
#| echo: true

fig = px.line(df_ee['Electricity Generation, SF']).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal",
          font=dict(
               family="sans-serif",
               size=12,
               color="black"
               )
     ))
fig.show()


fig = px.line(df_ee[['Electricity Generation, SWDA','Electricity Generation, CA']]).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"))
fig.show()
```
:::


::: {.callout-tip title="Истории развития методов декомпозиции" collapse="true" #tip-historysa}

Разработано большое количество методов сезонной корректировки, наиболее распространенные из них описаны, в частности, в @eurostatsahandbook2018. История развития методов сезонной корректировки отражена в [@fischer1995decomposition; @den1991seasonal], описание ранних методов можно найти в [@bobrov1930]. 

Большинство методов сезонной корректировки можно отнести к одной из двух групп. Первую группу составляют алгоритмы, основанные на методах линейной фильтрации, единых для многих обрабатываемых временных рядов. Другими словами, характеристики используемых фильтров либо совсем не зависят от свойств обрабатываемых временных рядов, либо на них можно оказывать некоторое влияние, изменяя значения небольшого числа параметров методов. Наиболее известными представителями этой группы являются методы семейства X-11 [@Shiskin1967; @findley1998new], разработанные, в основном, в Бюро переписей США и используемые в статистических органах многих стран мира. Наиболее известные представители этой группы – методы семейства X-11: X-11, X-11-ARIMA, X-12-ARIMA.

Методы этого семейства – стандарт де-факто в статистических службах многих стран мира. Их сильная сторона в пдаптивности – способности подстраиваться под любые изменения сезонных волн и другие особенности динамики рядов. Недостаток в том, что считается необходимым калибровать модель для каждого ряда индивидуально, см. [@eurostatsahandbook2018]

Ко второй группе можно отнести методы сезонной корректировки, основанные на моделях, которые индивидуально строят для каждого корректируемого временного ряда. В этом случае свойства модели, на основе которой производится декомпозиция, существенно зависят от свойств обрабатываемого временного ряда (подробнее см. [@den1991seasonal;@fischer1995decomposition]). К этой группе относится, в частности, разработанный в Банке Испании метод SEATS, продвигаемый Евростатом. 

Несмотря на то что с теоретической точки зрения методы второй группы обладают несомненными преимуществами, на практике они пока еще далеко не всегда позволяют получать более качественные результаты. Кроме того, поскольку развитие и практическое использование методов первой группы началось гораздо раньше, то эти методы получили гораздо более широкое распространение, а соответствующие пакеты программ достигли зрелости. 

Алгоритмы обоих семейств реализованы в стандартных пакетах Eviews, SPSS, SAS, Gauss, Grelt, R и так далее. Большинство из данных пакетов в качестве ядра используют пакет [X-13ARIMA-SEATS](https://www.census.gov/data/software/x13as.Recent_News.html#list-tab-635278563) Бюро переписей. В ЕС в качестве стандарта используют семейство пакетов [Demetra](https://joinup.ec.europa.eu/collection/statistics/solution/demetra), разрабатываемых Национальным банком Бельгии и Евростатом.  Рекомендации по работе с пакетом [@grudkowska2017jdemetramanual; @grudkowska2017jdemetrayuserguide].

Методы сезонной корректировки, основанные на определении не изменяющихся от года к году индексов сезонности, в силу своей простоты вполне пригодны для использования в учебных целях в качестве иллюстрации явления сезонности, для оценки масштаба сезонной составляющей, для описания подходов к сезонной корректировке и т. п., однако они не используются в профессиональной практике анализа данных. Их непригодность для практического использования была осознана многие десятилетия назад (см., например, работу начала XX в. [@persons1927] и вышедшие много лет назад труды конференций [@shiskin1960seasonal; @zellner1978seasonal]). 

В русскоязычной литературе вопросы декомпозиции освещены слабо. Причины отчасти носят исторический характер. В эпоху планового развития (1930–1990 гг.) экономическая конъюнктура систематически не анализировалась. Необходимо проявлять осторожность при чтении русскоязычной литературы по экономической статистике. Рекомендуем начать знакомство с сезонностью со следующих материалов [@cleveland1983seasonal; @findley1998new;@den1991seasonal; @gomez2001seasonal; @bell2012economic; @eurostatsahandbook2018].
:::

#### Преобразования, которые нельзя считать сезонной корректировки

Поскольку при анализе макроэкономической динамики от исследователя требуется корректное применение существующих программ сезонной корректировки, а не их разработка, детали метода сезонной коррекции рассматривать здесь не будем. Ограничимся лишь замечанием о том, какие преобразования временных рядов нельзя считать методами сезонной корректировки. 

В качестве метода сезонной корректировки иногда рекомендуют использовать метод укрупнения интервалов, который состоит в том, чтобы на основе месячного или квартального временного ряда, содержащего сезонную составляющую, получить временной ряд в годовом выражении, который сезонной составляющей не содержит по определению. Несмотря на то что метод укрупнения интервалов, несомненно, позволяет избавиться от сезонной составляющей, он не решает задачу сезонной корректировки, а лишь обходит ее. В самом деле, смысл проведения сезонной корректировки состоит в том, чтобы придать уровням временного ряда сопоставимость в пределах года. Другими словами, проведение сезонной корректировки является средством повышения на порядок точности измерений во временной области: не проводя сезонной корректировки можно идентифицировать изменения тенденций за время порядка года, тогда как ее проведение позволяет идентифицировать изменения за время порядка месяца. Метод же укрупнения интервалов не позволяет повысить точности идентификации изменения тенденций во временной области. Рекомендация использовать метод укрупнения интервалов для проведения сезонной корректировки сродни рекомендации использовать гильотину для борьбы с головной болью.

Также встречаются рекомендации проводить для удаления сезонной составляющей сглаживание скользящим средним с тем, чтобы получаемая в результате достаточно гладкая оценка трендовой составляющей не содержала сезонной составляющей. Хотя этот метод также позволяет удалить сезонную составляющую, его нельзя считать методом сезонной корректировки, поскольку вместе с сезонной составляющей он, вообще говоря, удаляет (или искажает) и высокочастотные составляющие компоненты тренда и конъюнктуры, анализ которых обычно представляет основной интерес. 

Таким образом, и этот прием не позволяет повысить точность идентификации изменения тенденций во временной области. 

Также встречаются рекомендации использовать методы на основе разложения в ряд Фурье для проведения сезонной корректировки. Эти методы, как и только что рассмотренные, основанные на использовании не изменяющихся индексов сезонности, пригодны лишь для случая строгой периодичности и поэтому в общем случае не являются адекватными.

Наконец, нередко встречаются рекомендации использовать методы сезонной корректировки, сводящиеся к построению индексов сезонности, под которыми понимают набор коэффициентов (12 для месячных данных и 4 для квартальных), на которые в полной аналогии с описанным выше простейшим методом календарной корректировки делят уровни соответствующих месяцев или кварталов с целью исключения сезонной волны.

В отличие от двух предыдущих методов использование таких не изменяющихся от года к году индексов сезонности позволяет проводить сезонную корректировку. Проблема здесь состоит в том, что этот класс методов пригоден для проведения сезонной корректировки лишь в единственном частном случае, когда сезонный эффект представлен мультипликативно, а форма сезонной волны не меняется со временем, т. е. для одного из случаев строгой периодичности. Вместе с тем сезонные волны, как правило, с течением времени эволюционируют (см., например, рис. 2.5,а), поэтому использование методов, сводящихся к построению не изменяющихся от года к году индексов сезонности, приводит к тому, что для каких-то периодов сезонная составляющая может быть удалена не полностью, а для каких-то - с избытком, т. е. может возникнуть ситуация избыточной или недостаточной корректировки^[англ. over- или under-adjustment]. В результате часть сезонной составляющей (с положительным или отрицательным знаком) попадает в сезонно скорректированный ряд, искажая его краткосрочные тенденции. Такой эффект называют эффектом просачивания^[англ. leakage]. 

Мы познакомися с ним в следующем разделе.

#### Иллюстрация эффекта просачивания сезонной составляющей

Эффект просачивания сезонной составляющей состоит в том, что по мере поступления новых данных, алгоритмы сезонной коррекции уточняют оценку вкладов различных компонентов временного ряда в прошлом. Иногда такое уточненение действительно отражает растущую точность, с которой мы идентифицируем вклады сезонности или иных составляющих. Однако в других случаях новые данные могут искажать наше представление о прошлом. Такие искажения могут иметь различную природу. 

Например, изменение природы рынка товара может привести к изменению характреа сезонности. Так, рынок цемента до 1991 г. был ограничен со стороны предложения - покупатели цемента были готовы покупать любые объемы доступные на рынке, а загрузка мощностей была близка к полной. В результате сезонность ряда была не выражена. Впоследствии, рынок цемента стал конкурентным и спрос начал быть ограничением для производства. Спрос строителей на цемент максимален в периоды года, которые лучше подходят климатически для выполнения работ, т.е. в относительно теплые и сухие месяцы, и снижается в периоды, слабо подходящие для работ. Очевидно, что попытка кооректировать сезонность для объединенного ряда двух таких режимов скорее будет искажать декомпозицию динамики для каждого из них.

Частным случаем эффекта просачиваения является постепенное уточнение коэффициентов сезонной коррекции по мере поступления новых данных. Рассмотрим, как появляение новых данных влияет на наши оценки динамики выработки электроэнергии. Для этого создадим две таблицы для агрегирования винтажей оценок динамики ряда и коэффициентов сезонной коррекции. 


```{python}
df_ee_leak = df_ee[['Electricity Generation, CA']].copy(deep=True)
df_ee_leak_sf = df_ee[['Electricity Generation, CA']].copy(deep=True)
```

Теперь мы можем запустить цикл коррекции с расширяющимся окном. Параметры нашего расчета таковы, что мы начинаем оценку с первых 48 наблюдений, т.е. первых 4-х лет, и затем добавляем по 12 месяцев за одни цикл:

```{python}

#| output = false
#| warning = false
#| error = false

li_date_ix = df_ee_leak.index 

for dt in li_date_ix[48::12]:
     x13_res = x13_arima_analysis(df_ee_leak['Electricity Generation, CA'].loc[:dt], log=True, x12path=fd_x13, trading=True)
     df_ee_leak[dt] = x13_res.seasadj
     df_ee_leak_sf[dt] = df_ee_leak['Electricity Generation, CA'].loc[:dt].div(x13_res.seasadj)
```

На @fig-ch_econ_dyn_econts_electricity_seasonal_comp_cycle показаны как различались оценки временного ряда электроэнергии в различные периоды времени. В частности видно, как заметно были уточнены вниз уровни производства электроэнергии в 4кв21 по мере поступления новых данных, которые показывали на расширение амплитуды сезонной волны.

```{python}

#| label: fig-ch_econ_dyn_econts_electricity_seasonal_comp_cycle
#| fig-cap: "Винтажи скорректированного на сезонность производства электроэнергии"
#| layout-ncol: 1
#| column: page
#| echo: true

df_ee_leak = df_ee_leak.drop(columns=['Electricity Generation, CA'])

fig = px.line(df_ee_leak).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     )
fig.show()
```

Аналогичное представление об эволюции сезонной волны предлагает диагностический график на @fig-ch_econ_dyn_econts_seasonal_wave_ee. Графике по оси Х отложены месяцы года, а по Y величина сезонного коэффициента. Линия для одного месяца отражает динамику коэффициента сезонной коррекции для всех лет в наблюдаемом ряде. Тренд коэффициентов в сторону единицы со временем говорит о сокращении амплитуды сезонных колебаний, а от единицы - о расширении ее амплитуды. 

```{python}

#| label: fig-ch_econ_dyn_econts_seasonal_wave_ee
#| fig-cap: "Эволюция сезонной волны производства электроэнергии"

df_sf = df_ee[['Electricity Generation, SF']].copy(deep=True)

ix_dt_y_max, ix_dt_y_min = max(df_sf.index.year), min(df_sf.index.year)
lim_min, lim_max = -0.3, 0.3

shifter = lambda t:lim_min + ((lim_max-(lim_min))/(ix_dt_y_max-ix_dt_y_min))*(t-ix_dt_y_min)
# import numpy as np
# shifter = lambda a: np.interp(a, (ix_dt_y_min, ix_dt_y_max), (lim_min, lim_max)

df_sf ['X'] = df_sf.index.month + df_sf.index.year.map(shifter)

df_sf ['Month'] = df_sf.index.month

df_sf_t = df_sf .pivot(values='Electricity Generation, SF',index='X',columns='Month')

fig = px.line(df_sf_t).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_range=[-0.5,12.5]
     , yaxis_range=[0.8,1.3]
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"
          ,orientation="h"
     ))
fig.show()
```

Как видно из оценок для выработки электроэнергии, для этого индикатора амплитуда сезонных колебаний снижалась со временем. В принципе по мере адаптации и развития технологий снижение сезонности, то есть чувствительность к погодному циклу, характерно для многих инидикаторов - например, сезонность безработицы заметно снизилась за последние 20 лет. Однако, есть и исключения из правила.

Так, другим примером просачивания сезонности и значительных изменений сезонной волны может быть результатом случайно совпадающих однонарправленных шоков в течении ряда лет. Так, шоки на нетфтяном рынке приводили к ослаблению валютного курса в первых кварталах 2015, 2016 и 2020 годов. Эти совпадающие ослабления валютного курса обычно сопровождалось аномальным ростом цен на продукты питания и часть товаров, чувствительных к валютному курсу. В условиях достаточного масштаба и небольшой длинны временного ряда индекса потребительских цен таких 2-3 эпизодов достаточно для того, чтобы значительно исказить оценки сезонной компоненты. Причем, такие искажение будут воздействовать как на свежие наблюдения, так на прошлые. В этом случае, алгоритм сезонной коррекции скорее всего будет переоценивать размер сезонной волны для первых кварталов лет, а следовательно занижать оценку роста цен с коррекцией на сезонность для этой части года.

Вместе с тем, однозначно интерпретировать изменение сезонной волны и в этом случае сложно. Так, на форму сезонности могло повлияет одновременное с первыми шоками валютного курса в введение эмбарго на импорт продовольствия, прежде всего фруктов и овощей и недружественных стран в 2014 году. Это эмбарго в частности привело к сокращению географии поставок продовольствия, а следовательно могло увеличить амплитуду сезонной волны. 

На @fig-ch_econ_dyn_econts_seasonal_wave_food показана оценка эволюции сезонной волны потребительских цен овощей и фруктов. Как видно, в последние годы коэфициенты для зимних месяцев, а также августа и сентября скорее отдаляются от единицы, что говорит о росте амплитуды сезонных колебаний. Такие оценки согласуются и с общими наблюдениями о росте частоты аномальных изменений цен в этой категории потребительских товаров: например, в июне 2020 г. [впервые за историю наблюдения было зафиксировано снижение цен дефляция](https://www.vedomosti.ru/economics/articles/2022/07/08/930586-rosstat-zafiksiroval-deflyatsiyu), в 2023 [снижение цен было зафиксировано в последюю неделю февраля](https://www.rbc.ru/economics/01/03/2023/63ff3b2c9a794768be249b49).

```{python}

#| label: fig-ch_econ_dyn_econts_seasonal_wave_food
#| fig-cap: "Эволюция сезонной волны потребительских цен овощей и фруктов"

df_cpi_fv = pd.read_excel(r'./data/cpi_m_fv.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     [['MM']] \
     .dropna() \
     .resample('M').last() \
     .div(100).add(1).cumprod() \
     .pipe(lambda ts: ts.div(ts.iloc[0]))


x13_res = x13_arima_analysis(df_cpi_fv['MM'], log=True,  x12path=fd_x13)
df_cpi_fv['SA'] = x13_res.seasadj
df_cpi_fv['SF'] = df_cpi_fv['MM'].div(df_cpi_fv['SA'])

ix_dt_y_max, ix_dt_y_min = max(df_cpi_fv.index.year), min(df_cpi_fv.index.year)
lim_min, lim_max = -0.3, 0.3

shifter = lambda t:lim_min + ((lim_max-(lim_min))/(ix_dt_y_max-ix_dt_y_min))*(t-ix_dt_y_min)
# import numpy as np
# shifter = lambda a: np.interp(a, (ix_dt_y_min, ix_dt_y_max), (lim_min, lim_max)

df_cpi_fv['X'] = df_cpi_fv.index.month + df_cpi_fv.index.year.map(shifter)

df_cpi_fv['Month'] = df_cpi_fv.index.month

df_cpi_fv_t = df_cpi_fv.pivot(values='SF',index='X',columns='Month')

fig = px.line(df_cpi_fv_t).update_layout(
     xaxis_range=[-0.5,12.5]
     , yaxis_range=[0.8,1.2]
     , yaxis_title="Сезонный фактор"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"
          ,orientation="h"
     ))
fig.show()

```

### Нерегулярная составляющая динамики

В основе нерегулярной составляющей динамики^[англ. irregular component, irregular variations] лежат вариации, обусловленные ошибками сбора и первичной обработки информации, неритмичностью протекания экономических процессов, простоями, срывами поставок, авариями, учетом части продукции, произведенной или потребленной в одном месяце, в отчетности другого месяца и прочими подобными факторами, не имеющими прямого отношения к интенсивности анализируемого экономического процесса, а лишь зашумляющими ее.

Например, в 2019 г. оценка индекса промпроизводства была искажена из-за неверно переданных сведений из Ямало-Ненецкого округа по добыче газа, из-за которого значения оказались аномальными. Росстату пришлось отозвать оценки рекордного  [роста промпроизводства](https://www.vedomosti.ru/economics/articles/2019/05/23/802272-rosstat) и уточнять ее вне обычного календаря пересмотра статистики.

Иллюстрацию неритмичности протекания экономических процессов, простои дает период пандемии COVID-19:, во втором квартале 2020 г., около 1 млн человек находили в простое, еще 1,3 млн человек работали [неполный рабочий день](https://iz.ru/1069641/ekaterina-vinogradova/kvartalnyi-vychet-46-mln-rossiian-urezali-zarplatu-iz-za-covid). Срывы поставок были распространены в 2022 г., когда из-за санкций западные поставщики массово отказывались от работы с российскими компаниями из-за угрозы вторчиных санкций. Например, об этом [заявляли в “Автовазе”](https://www.vedomosti.ru/business/news/2023/11/20/1006728-prezident-avtovaza-ob-otkazah-v-sotrudnichestve). Кроме того, с 2022 г. более выражены стали влияния аварий, в том числе связанных с боевыми действиями в приграничной зоне. В частности, пострадала [птицефабрика в Белгородской области](https://rtvi.com/news/belgorodskaya-oblast-popala-pod-obstrel-est-pogibshij-i-postradavshie-povrezhdena-pticzefabrika/), что могло повлиять на предложение яиц, спустя полгода возник дефицит. Наконец, нерегулярная составляющая может быть связана с разрывом экономических связей. Например, в России могло упасть производство двигателей и других автокомпонентов из-за ухода автомобильных концернов. 

Заметим, что в работах, посвященных декомпозиции экономических временных рядов, обсуждаемую составляющую динамики, как правило, называют нерегулярной^[англ. irregular], а не случайной^[англ. random]. Первый термин, в отличие от второго, не предполагает непременно стохастической трактовки данной составляющей. Это связано, в частности, с тем, что нерегулярная составляющая динамики может включать в себя выбросы и другие особенности, не имеющие случайной природы.

Оценим нерегулярную составляющую для ряда выработки электроэнергии:

```{python}
x13_res = x13_arima_analysis(df_ee['Electricity Generation, CA']
     , log=True
     , x12path=fd_x13)
```

Алгоритм сезонной коррекции вернет оценку нерегулярной составляющей в качестве множителя или коэффицентам. Поэтому, чтобы получить ее абсолютное значение, нам предется домножить эту оценку на величину исходного показателя выработки электроэнергии с календартной корректировкой:

```{python}

df_ee['Electricity Generation, I'] = (x13_res.irregular).sub(1).mul(df_ee['Electricity Generation, CA'])

```

На @fig-ch_econ_dyn_econts_sa_irregular_component показана оценка нерегулярной составляющей временного ряда производства электроэнергии и этот ряд с элиминированными календарной, сезонной и нерегулярной составляющими.

:::  {layout-ncol=2 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_sa_irregular_component
#| fig-cap: "Производство электроэнергии"
#| fig-subcap:
#|   - "Нерегулярная компонента производства электроэнергии"
#|   - "Выработка с сезонной и календарной коррекцией"
#| layout-ncol: 2
#| column: page
#| echo: false


fig = px.line(df_ee['Electricity Generation, I']).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal",
     ))
fig.show()


fig = px.line(df_ee[['Electricity Generation, SWDA','Electricity Generation, CA']]).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"))
fig.show()

```

:::

Как и для календарной составляющей, масштаб нерегулярной составляющей интервальных экономических временных рядов, как правило, увеличивается в относительном выражении с уменьшением шага по времени. Причина этого состоит в том, что при укрупнении шага по времени (скажем, при получении годовых данных суммированием месячных значений) нерегулярные колебания частично погашают друг друга. Сказанное не относится к моментным рядам. 

Если исходный временной ряд рассматривается как совокупность календарной, сезонной, нерегулярной и трендовой составляющих динамики, то после проведения календарной и сезонной корректировок для завершения декомпозиции экономического временного ряда остается отделить трендовую составляющую от нерегулярной. Для этого обычно предполагают, что трендовая составляющая является в некотором смысле гладкой, что оправдывает применение методов сглаживания^[англ. smoothing] для ее идентификации (см., например, [@eurostatsahandbook2018]). Получающийся в результате календарной и сезонной корректировок и сглаживания временной ряд можно рассматривать как оценку компоненты тренда и конъюнктуры исходного ряда. 

Следует отметить, что идентификация нерегулярной составляющей может вызывать сложности, если ее поведение меняется со временем. Одним из примером таких изменений является изменяющаяся со временем дисперсия нерегулярной компоненты - феномен, которые в статистике называется гетероскедастичностью. Современные методы сезонной коррекции адаптированы для работы с рядами, в которой [нерегулярная компонента гетероскедостична](https://www.imf.org/external/pubs/ft/qna/2000/textbook/ch8.pdf).

### Компонента тренда и конъюнктуры

То, что остается после элиминирования календарной, сезонной и нерегулярной составляющих, называют компонентой тренда и конъюнктуры (синонимы - трендовая составляющая динамики, trend-cycle component).

Она определяет тенденцию изменения уровней временного ряда, не искаженных календарными, сезонными и нерегулярными эффектами. Чаще всего именно она рассматривается как информативная в задачах анализа экономической динамики, тогда как календарная, сезонная и нерегулярная составляющие динамики обычно рассматриваются как неинформативные.

Подчеркнем, при декомпозиции временного ряда под компонентой тренда и конъюнктуры экономического временного ряда понимается одна из его составляющих динамики, т. е. временной ряд. Его уровни могут возрастать или снижаться с течением времени, могут быть неизменными, периоды роста могут сменяться периодами спада. Относительно тенденций такого временного ряда не делается никаких априорных предположений. В отличие от этого в разделе эконометрики, посвященном анализу временных рядов, под трендом обычно понимается наличие некой монотонной зависимости ряда от времени (например, см. [@канторович2003лекции]). 

Алгоритм декомпозиции временного ряда позволяет выделить компоненту тренда и цикла одновременно с сезонной, нерегулярной и трендовой составляющих. ^[Некоторые методы позволяют производить разложение ряда сразу на три составляющие (например, используемый Федеральным статистическим управлением [ФРГ метод BV4](https://www.destatis.de/EN/Methods/Seasonal-adjustment/decomposition-bv41.pdf?__blob=publicationFile))]. Извелечем оценки компоненты тренда и цикла, полученные нами при сезонной коррекции.

```{python}

df_ee['Electricity Generation, TC'] = x13_res.trend 

```

На @fig-ch_econ_dyn_econts_sa_trendcycle_component показан график оценки компоненты тренда и конъюнктуры временного ряда производства электроэнергии. Как видно, компонента тренда и конъюнктуры определяет тенденцию изменения уровней временного ряда, не искаженных календарными, сезонными и нерегулярными эффектами.

:::  {layout-ncol=2 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_sa_trendcycle_component
#| fig-cap: "Производство электроэнергии"
#| fig-subcap:
#|   - "Оценка компоненты тренда и цикла"
#|   - "Ряд с сезонной коррекцией"
#| layout-ncol: 2
#| column: page
#| echo: false

fig = px.line(df_ee['Electricity Generation, TC']).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal")
     , legend_title=None)
fig.show()

fig = px.line(df_ee[['Electricity Generation, SWDA','Electricity Generation, TC']]).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal")
     , legend_title=None)
fig.show()

```
:::

### Вековой тренд и циклы

В дополнение к четырем перечисленным составляющим динамики можно выделять и другие, состав которых определяется решаемой задачей и свойствами объекта исследования. Так, в составе компоненты тренда и конъюнктуры бывает можно выделить долгосрочный тренд (синонимы - вековой тренд, secular trend) с наложенными на него циклами (cycles) различной продолжительности. 

В зависимости от решаемой аналитиком задачи определение того, что следует считать долгосрым трендом будет розниться. В зависимости решаемой задаче и инструменты идентификации долгосрочного тренда могут отличаться. В ряде случаев тренд возможно предположить линейным для логорифмов временного ряда. В других случаях удобно использовать статистические фильтры для идентификации долгосрочного тренда. 

В настоящем примере мы используем популярный фильтр Ходрика-Прескота для оценки долгосрочного тренда в динамике выработки электроэнергии.

```{python}

from statsmodels.tsa.filters.hp_filter import hpfilter

```

Большинство статистических фильтров имеют параметр, который задает жесткость тренда. Для фильтра Ходрика-Прескотта это параметр $\lambda$, величина которого определяется насколько оценка тренда будет гладкой. В данном случаем, мы выбираем значение $\lambda=4,000$ руководствуясь общим правилом для данных месячной частоты.

```{python}

cycle, trend = hpfilter(df_ee['Electricity Generation, TC']
     , lamb = 14400)

df_ee['Electricity Generation, ST'] = trend
df_ee['Electricity Generation, ST Gap'] = cycle

```

На @fig-ch_econ_dyn_econts_longtermtrend изображены оценки долгосрочного тренда выработки электроэнергии и отклонения компоненты тренда и цикла от долгосрочного тренда. В некоторых задачах анализа экономической динамики оценки отклонения от тренда могут иметь сходный или более значительный уровень интереса, как и идентификация скажем точек изменения тендеции от роста к спаду показателя.

:::  {layout-ncol=2 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_longtermtrend
#| fig-cap: "Тренд выработки электроэнергии"
#| fig-subcap:
#|   - "Оценка тренда выработки электроэнегрии"
#|   - "Трендовое значение выработки электроэнергии и отклоения от тренда"
#| layout-ncol: 2
#| column: page
#| echo: false

fig = px.line(df_ee[['Electricity Generation, ST','Electricity Generation, TC']]).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"
     )
     , legend_title=None)
fig.show()

fig = px.bar(df_ee[['Electricity Generation, ST','Electricity Generation, ST Gap']]).update_layout(
     yaxis_title="Миллион КВатт"
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"
     )
     , legend_title=None)
fig.show()

```

:::

Чем длиннее временной ряд, тем большее число циклических составляющих может быть в нем выделено. Всякая циклическая составляющая динамики может, в принципе, служить объектом содержательного исследования. 

Подчеркнем, что выделение циклических составляющих динамики из компоненты тренда и конъюнктуры, вообще говоря, может быть произведено различными способами. Разложение экономического временного ряда на составляющие динамики обусловлено, с одной стороны, его свойствами, а с другой стороны, целями исследования. Первые - объективны (в той мере, в которой они отражают свойства объекта исследования), вторые - субъективны. В результате один и тот же ряд при решении разных задач анализа экономической динамики может быть представлен в виде совокупности различных составляющих динамики, подобно тому, как в задачах механики Земля может рассматриваться как материальная точка, как полупространство, как однородный шар и множеством других способов в зависимости от решаемой задачи.

### Событийная составляющая динамики

Также иногда выделяют в отдельную составляющую и совокупность результатов воздействия неординарных событий на динамику показателя (событийная составляющая динамики, unusual events). Такими неординарными событиями может быть неурожай, землетрясение (Фукусима), наводнение, внешний шок (санкции), крупные аварии (грязная нефть в нефтепроводе), пандемия, изменения в законодательстве, которое значительно ограничивает или увеличивает предложение на рынке товаров. Одним из таких примеров может служить уход иностранных мировых брендов с российского рынка, что повлияло на предложение в разных отраслях (от производства одежды и мебели до производства автомобилей, компьютеров, самолётов).

Событийную составляющую иногда выделяют из нерегулярной, а иногда – из компоненты тренда и конъюнктуры в зависимости от поведения этих рядов. На @fig-ch_econ_dyn_econts_sa_event_export приведен пример временного ряда импорта товаров, содержащего выраженную событийную составляющую. На графике заметны шоки в период эпидемии COVID в 2020 г., которые сопровождались перебоями в торговле товарами, как за счет ограничений,связанных с распространением эпидемии, так и приостановкой работы ряда предприятий за рубежом. 

:::  {layout-ncol=1 .column-page}
```{python}

#| label: fig-ch_econ_dyn_econts_sa_event_export
#| fig-cap: "Временные ряды с выраженной событийной составляющей: Импорт товаров, млрд. долл."
#| layout-ncol: 1
#| column: page
#| echo: false

ts_x = pd.read_excel(r'./data/tb_xm_m.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     [['Exports']] \
     .dropna() \
     .resample('M').last()

fig = px.line(ts_x).update_layout(
     yaxis_title="$ млрд."
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"))
fig.show()

```
:::

Еще один пример временного ряда с выраженной событийной составляющей - это ряда экспорта природного газа Россией в ЕС. Его динамика приведена на @fig-ch_econ_dyn_econts_sa_event_natgas. В данном случае контекст важен для анализа данных. В этом случае на экспорт газа из России повлиял подрыв газопровода Nord Stream в 2022 году. В результате 2023 году экспорт газа [в страны ОЭСР снизился на 42%](https://www.vedomosti.ru/business/articles/2024/01/27/1017014-postavki-gaza-po-truboprovodam 
) - до минимума с начала 1970-х. 

:::  {layout-ncol=1 .column-page}
```{python}

#| label: fig-ch_econ_dyn_econts_sa_event_natgas
#| fig-cap: "Временные ряды с выраженной событийной составляющей: Импорт товаров, млрд. долл."
#| layout-ncol: 1
#| column: page
#| echo: false

ts_natgas = pd.read_excel(r'./data/natgas.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     [['Nat Gas']] \
     .dropna() \
     .resample('M').last()

fig = px.line(ts_natgas).update_layout(
     yaxis_title="$ млрд."
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal")
     , legend_title=None)
fig.show()

```
:::

Помимо протяженных во времени флуктуаций к событийной составляющей динамики могут быть отнесены и выбросы (outliers), т. е. резкие отклонения от тенденции (в смысле значительного превышения масштаба нерегулярной составляющей в окрестности соответствующего периода), наблюдающиеся на протяжении лишь одного периода или группы изолированных периодов. Такие выбросы могут быть связаны с паниками, объявлениями радикальных мер экономической политики или с ошибками построения временных рядов статистической службой. Таким образом, выбросы могут быть информативными и неинформативными - нести информацию об исследуемом процессе или нет. Например, выбросы, связанные с погрешностями оценки динамики рядов статистической службой скорее следует выделять выделять в отдельную составляющую динамики, тогда как события связанные с резкими колебаниями спроса и предложения, чаще, следует рассматривать как часть компонентов цикла и треда или нерегулярной копоненты. 

<!-- Еще один, менее тривиальный, пример, дающий возможность выделения событийной составляющей динамики, приведен на @fig-ch_econ_dyn_econts_sa_event_wheat. Этот график иллюстрирует динамику урожайности зерновых хлебов в дореволюционной России с 1801 г. по 1915 г. В то время измеряли так называемый урожай/сам, т. е. отношение массы собранного урожая к массе использованного семенного материала. В первой половине рассматриваемого интервала времени динамика урожайности, в первом приближении, не демонстрировала тенденции роста или спада, тогда как во второй половине, после отменены крепостного права в 1861 г., явно просматривается тенденция роста. 

Если задача исследования предполагает анализ динамики урожайности вне связи с анализом каких-либо событий, например, если изучается влияние некоторого фактора, действовавшего на протяжении всего периода (скажем, солнечной активности, измеряемой числами Вольфа), то в качестве адекватной оценки векового тренда можно рассматривать оценку типа той, что показана на @fig-ch_econ_dyn_econts_sa_event_wheat, а. Если же задача состоит в анализе влияния на динамику урожайности какого-либо события, например, реформы 1861 г., то нарастающее отклонение от тенденции, существовавшей до 1861 г., должно быть отнесено на счет событийной составляющей динамики (@fig-ch_econ_dyn_econts_sa_event_wheat, б). Для других задач адекватной может быть трактовка этого роста как смены тенденции.  -->

### Истинная декомпозиция временного ряда

Совокупность всех составляющих динамики, за исключением нерегулярной (и, возможно, событийной), будем называть также регулярной составляющей динамики (regular component). Заметим, что "регулярность" не обязательно означает "гладкость". Так, календарная составляющая динамики определенно не является гладкой, сезонная составляющая может быть достаточно гладкой, а может и не быть таковой, компонента тренда и конъюнктуры может демонстрировать резкие скачки и изломы (резкие изменения первых разностей).

Возможность рассмотрения временного ряда как совокупности описанных выше составляющих динамики является спецификой экономических временных рядов - про произвольный временной ряд такого сказать нельзя. Кроме того, в анализе экономического временного ряда нет "единственно правильной" декомпозиции. Декомпозиция будет определяться свойствами объекта исследования, решаемой аналитиком задачей, а так же теми дополнительными знаниями о событиях, которые могли воздействовать на поведение ряда, которыми располагает аналитик. Такие знания могут помочь отличить информативный выброс от неинформативного, а так же отличить сезонные колебания от событийных. 

На @fig-ch_econ_dyn_econts_ee_decomp приведена итоговая декомпозиция ряда производства электорэнергии. Наша декомпозиция позволяет идентифицировать повторяющиеся сезонные волны в выработке, аномальные всплески в выработке электроэнергии в февралях 2022 и 2023 годов, а так же информативные изменения в уровне выработки компоненты тренда и цикла. 

```{python}

#| label: fig-ch_econ_dyn_econts_ee_decomp
#| fig-cap: "Тренд выработки электроэнергии"
#| layout-ncol: 1
#| column: page
#| echo: false

df_ee['Electricity Generation, SC'] = df_ee['Electricity Generation, CA'] \
     .sub(df_ee[['Electricity Generation, I','Electricity Generation, TC']].sum(axis=1))


fig = px.bar(df_ee[['Electricity Generation, TC','Electricity Generation, SC','Electricity Generation, I']]) \
     .update_layout(
          yaxis_title="Миллион КВатт"
          , xaxis_title=""
          , legend=dict(x=0.02,y=0.99,traceorder="normal")
          , legend_title=None)
fig.show()
```

## Макроэкономические временные ряды

Макроэкономические временные ряды^[macroeconomic time series] – ряды экономических показателей высокого уровня агрегирования или показателей, которые могут оказывать на них заметное влияние. Мапроэкономические временные ряды являются подмножеством множества экономических временных рядов. К макроэкономическим рядам не относят показатели уровня деятельности отдельной фирмы, муниципалитета уровня или  домохозяйства. Специфика макроэкономических временных рядов в том, что такие показатели получены путем агрегирования временных рядов и не могут быть получены путем непосредственной регистрации данных. Их получают расчетным путем, обрабатывая большие объемы первичной информации (непосредственно регистрируемой) с использованием сложных (и не всегда прозрачных) методик статистические службы и другие ведомства. Поэтому уровни и динамика макроэкономических рядов отражают как изменение свойств объекта исследования и существо экономических процессов, так и изменение инструмента измерения - методик построения соответствующих показателей.

Примерами макроэкономических временных рядов являются ряды валового внутреннего продукта, объема промышленной продукции, продукции сельского хозяйства, грузооборота транспорта, инвестиций в основной капитал, экспорта, импорта. Иллюстрации двух таких рядов приведены на @fig-ch_econ_dyn_econts_macrots.

В качестве примеров экономических временных рядов, не являющихся макроэкономическими, можно привести динамику продаж фирмы (если эта фирма не "Газпром" - т.е. предприятие, чья деятельность охватывает целую отрасль экономики), динамику урожайности зерновых в Московской области, стоимость набора потребительских товаров в [отдельном предприятии розничной торговли](https://dairynews.today/news/ekonomist-aleksandr-abramov-realnaya-inflyatsiya-v.html).

:::  {layout-ncol=2 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_macrots
#| fig-cap: "Примеры макроэкономических временных рядов"
#| fig-subcap:
#|   - "Индекс ВВП в сопоставимых ценах по Российской Федерации"
#|   - "Индекс потребительских цен по Российской Федерации"
#| layout-ncol: 2
#| column: page
#| echo: false

ts_natgas = pd.read_excel(r'./data/gdp_q.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     [['GDP, P21 SNA08']] \
     .dropna() \
     .resample('Q').last()

fig = px.line(ts_natgas).update_layout(
     yaxis_title="$ млрд."
     , xaxis_title=""
     , legend=dict(
          x=0.02,
          y=0.99,
          traceorder="normal"))
fig.show()


fig = px.line(ts_cpi_m).update_layout(
     yaxis_title="Индекс (12М2001 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()
```
:::

Следует отметить, что задачи анализа макроэкономической динамики могут быть математически некорректными в том смысле, что использование лишь информации, содержащейся в членах временного ряда, может быть недостаточно для корректного анализа. В общем случае, исследователю требуется знание более широкого контекста для корректного анализа. Два основных источника изменений в поведении макроэкономических временных рядов - это изменение и эволюция экономической системы и изменение методик построения макроэкономических временных рядов. 

Свойства объекта исследования и инструмента измерения изменяются со временем. Поэтому длинные временные ряды макроэкономических показателей во многих случаях представляют собой результат попытки измерить изменяющийся объект изменяющимся аршином (инструментом). Для достаточно длинных макроэкономических рядов свойств экономики могут настолько разниться для разных периодов, что их значения показателя относятся, вообще говоря, к разным системам. Яркий пример системы с интенсивно эволюционирующими свойствами – российская экономика, которая за период с 1991 г. проходит ряд трансформаций: от плановой экономики к рыночной, от режима относительно высокого уровня интеграции с глобальной экономикой к фрагментации рынков сырья и капитала. 

Кроме того, периоды интенсивных изменений в экономике, например, из-за кризисных явлений, могут приводит к снижению информативности макроэкономических временных рядов. Такое снижение ограниченности информации может быть связано с тем, что динамика агрегированного показателя скрывает за счет усреднения важные процессы может происходящие на уровне отдельных индикаторов - доходов отдельных предприятий, перебоев в поставках отдельных видов товаров и так далее. 

Одним из следствий таких постоянных изменений как объекта наблюдения, так и методик построения макроэкономических временных рядов приводит к тому, что добавление членов ряда, все далее отстоящих по времени от данного, дает все меньшее количество дополнительной информации о свойствах системы в данный период времени.

Компоненты тренда и конъюнктуры и другие составляющие динамики могут демонстрировать резкие скачки, изломы и другие особенности, являющиеся отражением крупных изменений в экономике (война, катастрофа, реформа). Такие особенности представляют собой проявления крайней степени несопоставимости данных. 

Достаточно типичным является отсутствие данных для некоторых периодов, а также наличие выбросов, обусловленных неординарными ситуациями или ошибками. Используемые методы должны позволять адекватно обрабатывать подобные ситуации. 

Таким образом, макроэкономические временные ряды являются весьма специфичными объектами обработки. Изложение, приводимое ниже, посвящено таким рядам, которые, как правило, имеют шаг по времени, равный месяцу, кварталу или году. В первую очередь будем рассматривать временные ряды помесячной динамики, поскольку высокие частоты несут основную часть информации. Использование макроэкономических временных рядов с шагом больше года (скажем, пятилетним) не слишком актуально в силу малой длины таких рядов и малого объема содержащейся в них информации. 

Использование экономических временных рядов с шагом существенно меньшим месяца выходит за рамки нашего рассмотрения, поскольку такие ряды обладают иной спецификой, отличной от рассмотренной выше. К числу таких рядов относятся, в частности, временные ряды финансовых показателей высокой частоты (котировки ценных бумаг, курсы валют и т. п.). Методы анализа таких данных хорошо разработаны, им посвящена обширная литература (см., например, @campbell1998econometrics).

При анализе макроэкономических временных рядов целесообразно учитывать их специфику. Рассмотрим более подробно, в чем она состоит. 

### Эволюция свойств экономической системы 

Макроэкономические временные ряды характеризуются неоднородностью содержащихся в них данных. В зависимости от степени такой неоднородности можно говорить о неполной сопоставимости данных во временной области, об их ограниченной преемственности или даже о низкой степени преемственности данных.

В качестве причин ограниченной преемственности макроэкономических данных укажем на эволюцию свойств экономики как объекта исследования и на эволюцию методик построения показателей. Всякая экономика является развивающейся системой, и это порождает проблемы проведения межвременных сопоставлений в ней. Эволюция свойств экономической системы приводит к тому, что значения одного и того же показателя для разных периодов относятся, вообще говоря, к разным системам. 

Ярким примером системы с интенсивно эволюционирующими свойствами является российская переходная экономика, принципы функционирования которой претерпели существенные изменения на протяжении 1990-х гг. К началу 1990-х гг. российская экономика была плановой, в ней, согласно [@Kornai1994], доминировали ресурсные ограничения. По окончании переходного периода была создана рыночная экономика, в которой доминируют спросовые ограничения. Помимо смены типа доминирующих ограничений в российской экономике за это же время произошли и другие важные изменения. К началу 1990-х гг. Россия была частью союзного государства, которое, в свою очередь, было частью социалистической системы, своего рода мира-экономики. В настоящее время Россия, как и прочие бывшие республики СССР, является независимым государством, социалистическая система прекратила свое существование и произошла масштабная переориентация экономических связей ее бывших составных частей. 

Разумеется, экономика далеко не всех стран и далеко не всегда претерпевает изменения, масштаб и интенсивность которых сравнимы с демонстрируемыми российской переходной экономикой. Тем не менее эволюция свойств системы зачастую дает о себе знать при проведении анализа макроэкономической динамики.

Приведем еще один, менее масштабный, пример, иллюстрирующий эволюцию свойств экономической системы. При проведении межвременных сопоставлений меньше всего проблем возникает при сравнении количеств и цен товаров, являющихся достаточно однородными, таких, как зерно, нефть, уголь, чугун, в отличие от таких плодов прогресса, как автомобили и бытовая техника, не говоря уже о персональных компьютерах и мобильных телефонах. Вместе с тем даже проведение сопоставлений, связанных с таким простым продуктом, как зерно, может сопровождаться серьезными трудностями. Так, сто лет назад, в начале XX в., до начала массового использования химических удобрений, зерно в России было весьма экологически чистым, а состав полезных веществ в нем был существенно иным, чем в эпоху химизации второй половины XX в. (скажем, процентное содержание белков в нем в начале XX в. было гораздо выше). После начала экономических реформ 1990-х гг. обедневшие производители сельскохозяйственной продукции перестали использовать химические удобрения в прежних количествах, что привело к улучшению качества зерна. Таким образом, на протяжении последнего столетия (и даже десятилетия экономических реформ) качество производимого в России зерна весьма существенно изменялось, что делает не вполне корректным непосредственное сопоставление количеств и цен производимого в разные периоды времени зерна. Если же учесть также изменение сортов зерновых, появление генетически модифицированных продуктов и т.п., то задача сопоставления становится еще более сложной даже и в этом сравнительно простом случае.

Эволюция свойств экономики порождает проблему ограниченности объема информации о ее состоянии в некоторый период времени, содержащейся в макроэкономическом временном ряде. Добавление членов ряда, все далее отстоящих по времени от данного, дает все меньшее количество дополнительной информации о состоянии системы в данный период времени. Увеличение же числа членов временного ряда за счет уменьшения шага по времени, с одной стороны, привносит специфические эффекты (возникают календарные и сезонные эффекты, масштаб которых зачастую растет с уменьшением шага по времени, увеличивается масштаб нерегулярной составляющей и т. п.), а с другой - наталкивается на отсутствие исходных данных (поскольку макроэкономические данные по технологическим соображениям, как правило, имеют шаг по времени не меньше одного месяца). 

Следствием эволюции свойств системы является то, что задачи анализа макроэкономической динамики часто бывают математически некорректными. Использования лишь данных, содержащихся в экономических временных рядах, может быть недостаточно для их корректного решения. Часто бывает необходимо привлечение дополнительной (в т. ч. нечисловой) информации о динамике экономической системы. В качестве примера такой ситуации укажем на рассмотренный выше пример резких флуктуаций динамики производства водки и ликеро-водочных изделий в России, обусловленных различными мерами государственного регулирования. Для корректной интерпретации динамики данного показателя необходимо привлечение дополнительной информации об этих мерах и о соответствующих им периодах времени. Другие примеры некорректности задач анализа макроэкономической динамики будут приведены ниже.

<!-- :::{.callout-caution collapse="false" title="Эволюция стркутуры системы и цикличность"}

Cчиталось, что в период между мировыми войнами экономики развитых стран Запада были в большей мере подвержены влиянию циклов экономической активности, чем после Второй мировой войны. Сейчас этот тезис подвергается сомнению на основе сопоставления методик измерения [20]. Дело, в частности, в том, что до Второй мировой войны в составе выпуска в большей мере учитывалось производство продукции, более подверженной цикличности, тогда как после войны возросла доля учитываемых услуг и продукции, менее подверженных влиянию цикличности.

::: -->

### Эволюция методик построения показателей 

Как уже было отмечено, значения агрегированных показателей определяются, в том числе, и методиками их построения. Методики же построения многих макроэкономических показателей не остаются неизменными, время от времени они уточняются или даже пересматриваются, т. е. они могут быть подвержены эволюции. В результате разные участки макроэкономических временных рядов могут быть построены по различающимся методикам. Это бывает особенно заметно у длинных рядов, охватывающих многие десятилетия. Динамичные условия переходного периода значительно усугубляют эту проблему. 

Эволюция методик построения макроэкономических показателей приводит к тому, что особенности динамики показателей, которые трактуются содержательно, могут быть обусловлены лишь изменениями методов измерения и не в полной мере соответствовать динамике анализируемых параметров системы. 

Например, в 2019 г. Росстат перешел на [новую методику учета доходов населения](https://www.rbc.ru/economics/19/03/2019/5c9108f69a79474300133f12). В частности, она предполагает увеличение доли зарплат в структуре доходов с 41 до 55%, но снижение доли доходов от предпринимательства с 7,6 до 6,3% и от собственности с 5,4 до 4,3%. Доля ненаблюдаемых доходов сократилась с 26 до 11,5%. В оценку доходов населения по статье «Оплата труда наемных работников» были добавлены показатели оплаты труда работающих в организациях без оформления договоров, наемных работников у физлиц и ИП (неформально занятые). Сравнение старой и новой методологий в применении к 2017 г. дали статистический прирост денежных доходов более чем на 1%: более 56 трлн руб. доходов по обновленной методике против 55,37 трлн руб. по прежней. 

Эволюция методики может быть обусловлена и территориальной несопоставимостью данных. Переходный период также изобилует примерами территориальной несопоставимости. Например, после того, как в 2014 г. Крым вошел в состав российских регионов, произошел [резкий скачок численности населения](https://www.vedomosti.ru/economics/articles/2023/04/14/970865-rosstat-planiruet-uchest-dannie-o-naselenii-novih-regionov-v-obschei-statistike) и других демографических показателей. По данным Росстата, в 2014 г. численность населения составляла 143,7 млн, а после присоединения Крыма на начало 2015 года – 146,3 млн человек. Эксперты говорили, что данные стали несопоставимы. Такая же проблема может встать и после интеграции данных от четырех новых регионов. 

<!-- Пример такой несопоставимости дает рис. 2.1,г, на котором показана динамика индекса валовой промышленной продукции СССР. Хотя все данные относятся к одному и тому же государству, но его границы на рассматриваемом интервале времени претерпели изменения за счет включения ряда территорий.  -->

::: {.callout-caution collapse="false" title="Методика и экономическая динамика"}

Изменения дезагрегированных временных рядов фиксируются напрямую. Примерами таких показателей являются цены на заданные виды товаров в определенной организации розничной торговли. Вместе с тем, для макроэкономических рядов зачастую значительные изменения могут быть связаны с тем, каким образом статистические службы меняют подходы к их агрегированию и периметру объектов, включаемых в определение показателя. Так, одними из заметных изменений в статистике валового ВВП России стал [переход](https://rosstat.gov.ru/storage/mediabank/UQQkH7Hp/Zavershena-rabota-po-vnedreniyu-polozheniy-SNS-1993.pdf) от системы национальных счетов версии 1993 г. (СНС 1993) к версии 2008 г. (СНС 2008) Две системы имеют значительные различия в периметре деятельности, которые учитывается в качестве конечного использования. Два наиболее значительных отличия СНС 2008 в учете вмененной ренты и части научных исследований и разработок в составе итоговой оценки ВВП. Такой учет привел к увеличению общей оценки размера ВВП, так и изменению ее динамических свойств - например, снижению доли нефтегазового сектора.

:::

В качестве еще одного примера эволюции методик приведем смену принципов измерения урожайности зерновых, произошедшую в России в XX в. В XIX в. в России, как мы уже отмечали, измеряли показатель урожай/сам, под которым понималось отношение собранного урожая к количеству использованного семенного материала. Скажем, если получали втрое большее количество зерна по сравнению с посеянным, то говорили об урожае сам/три (см. рис. 2.9). Такая система не была лишена смысла, так как урожай/сам можно рассматривать как частный показатель эффективности, поскольку он рассчитывается как отношение результата к одному из видов затрат. В XX в. стали измерять урожайность в центнерах с гектара, количество посеянных семян при этом перестало приниматься во внимание. Соответственно возникла проблема сопоставимости старых данных с новыми, которая в первом приближении может быть решена путем "сшивки" данных двух типов с использованием определенных преобразований данных. Однако различия, обусловленные разными принципами измерения урожайности, останутся и полученный таким образом временной ряд не может считаться полностью сопоставимым. 

Еще одна иллюстрация влияния методики на динамику макроэкономического временного ряда приведена на @fig-ch_econ_dyn_econts_macrots_invest. На @fig-ch_econ_dyn_econts_macrots_invest показана динамика официального российского индекса физического объема инвестиций в основной капитал. Такая динамика является вполне типичной для интервального временного ряда помесячного показателя с сильно выраженной сезонной волной. Однако тот же ряд после удаления календарной и сезонной составляющих демонстрирует скачки уровней на границах календарных лет, т. е. не вполне типичную динамику. Особенно заметны такие скачки в начале 1996, 1997, 1998, 1999 и 2002 гг.

:::  {layout-ncol=1 .column-page}

```{python}

#| label: fig-ch_econ_dyn_econts_macrots_invest
#| fig-cap: "Влияние особенностей методики на результаты краткосрочных сопоставлений"
#| fig-subcap:
#|   - "индекс физического объема инвестиций в основной капитал (месячные данные)"
#|   - "то же после проведения календарной и сезонной корректировок"
#| layout-ncol: 1
#| column: page
#| echo: false

ts_hhi_q = pd.read_excel(r'./data/hhi_q.xlsx'
     , sheet_name='X'
     , index_col='ds'
     ) \
     ['QQ'] \
     .dropna() \
     .resample('Q').last() \
     .div(100).add(1).cumprod()


x13_res = x13_arima_analysis(ts_hhi_q, log=True, x12path=fd_x13)

fig = px.line(pd.concat([ts_hhi_q, x13_res.seasadj], axis=1)).update_layout(
     yaxis_title="Индекс (4кв1998 = 1.0)"
     , xaxis_title=""
     , legend=dict(x=0.02,y=0.99, traceorder="normal")
     , legend_title=None
     )
fig.show()

```

:::

"Ступеньки" на границах календарных лет обусловлены, по всей видимости, досчетами уровней этого временного ряда с тем, чтобы изменения показателя за год, рассчитанные по данным в помесячном выражении, совпадали с изменениями соответствующего показателя в годовом выражении. Процедура приведения данных более высокой частоты в соответствие данным менее высокой частоты называется бенчмаркингом (benchmarking). В случае использования неадекватного алгоритма бенчмаркинга могут возникать искажения краткосрочных тенденций временного ряда, подвергаемого этой процедуре. Так, примитивный алгоритм бенчмаркинга состоит в домножении всех уровней временного ряда в помесячном выражении в пределах календарного года на одну и ту же константу. В этом случае на границах календарных лет могут возникать "ступеньки", т. е. может возникать проблема скачка (step problem). В результате происходит искажение краткосрочных тенденций, следствием чего может быть получение неверных содержательных выводов. Поэтому важно использовать лишь такие процедуры бенчмаркинга, которые не искажают краткосрочных тенденций (подробнее см. @lee2018quarterly). Помимо этого, с начала 2002 г. индекс физического объема инвестиций в основной капитал рассчитывается по несколько измененной методике, что, по всей видимости, внесло значительный вклад в резкое снижение уровней сезонно скорректированного временного ряда инвестиций в начале 2002 года. 

Вероятно, в ближайшие годы изменения в динамике макроэкономических рядов, связанных с изменениями в методике построения индикаторов будут связаны с переходами на новые принципы расчета показателей. Так, Росстат с 2021 г. [говорит о планах](https://www.vedomosti.ru/economics/articles/2023/11/30/1008520-v-pravitelstve-predlozhili-dat-rosstatu-onlain-dostup-k-dannim-biznesa) внедрить в расчет инфляции данные ККТ (биг-дата). При этом пока этого сделать не удалось по нескольким причинам. Например, данные не привязаны к конкретным торговым точкам из-за налоговой тайны, они передаются в “обезличенной форме”, при этом для расчета инфляции важно учесть географическую составляющую. Кроме того, есть технический момент - так как каждая организация сама вносит названия товаров в базу, автоматический сбор не позволяет правильно идентифицировать товар. потому в разных магазинах они отличаются. Например, только в Москве батончик Snickers имеет [1500 вариантов внутреннего наименования](https://www.vedomosti.ru/economics/articles/2023/08/07/988787-rosstatu-prishlos-otlozhit-otsenku-inflyatsii).

Фактически, у правительства уже есть агрегированная информация, основанная на больших данных и обновляющаяся в режиме реального времени, но она не публична (так называемые даш-борды). Количество информационных панелей, разработанных специалистами АЦ для обеспечения деятельности Координационного центра Правительства, [превысило 1000](https://ac.gov.ru/news/page/dasbordy-kc-avlautsa-mosnym-analiticeskim-instrumentom-raboty-pravitelstva-27663  
). Такие данные пока не внедряются в официальную статистику, так как это требует решения вопросов методологии и сопоставимости данных. При этом если говорить о статистике как об информации, которая влияет на принятие решений государства, то появился новый полуофициальный канал.

Активным пользователем и источником биг-дата в России является ФНС. Федеральная налоговая служба официально открывает в Дубне федеральный Центр обработки данных (ЦОД) — часть крупнейшего в истории РФ проекта в сфере big data, [сообщала ФНС в 2015 году](https://rspp.ru/events/news/fns-konsolidiruet-vse-nalogovye-dannye-v-odnom-data-tsentre--25985/). 
Налоговая служба имеет доступ к данным о торговых точках по всей стране после реформы ККТ 2018 г., когда каждая точка должна быть оборудована кассовым аппаратом, который может быть источников данных о динамике выручки и продаж. 

### Доминирование регулярных составляющих динамики 

Макроэкономические временные ряды зачастую имеют доминирующую компоненту тренда и конъюнктуры в случае годовых данных или доминирующую регулярную составляющую динамики (включающую компоненту тренда и конъюнктуры, сезонную и календарную составляющие) в случае месячных, квартальных и других данных с шагом по времени меньше года.

Такое доминирование регулярных составляющих динамики (т. е. весьма специфические соотношения между составляющими динамики) связано с тем, что макроэкономические временные ряды в отличие от временных рядов во многих других приложениях представляют собой ряды средних, т. е. ряды признаков больших совокупностей. Следствием осреднения является сравнительно слабая колеблемость (волатильность) многих макроэкономических временных рядов. Этим же можно объяснить и упоминавшуюся выше тенденцию к увеличению относительной колеблемости рядов динамики при уменьшении шага по времени. При построении макроэкономических временных рядов производится осреднение как в пространстве, так и во времени.

Например, с 2019 г. произошло укрупнение периода по реальным доходам населения – Росстат перешел с ежемесячной на ежеквартальную публикацию. Это привело к сглаживанию волатильности данных в течение года, однако очевидно затрудняет оперативный анализ тендеций в реальных доходах.

### Малая длина и краевые эффекты

Макроэкономические временные ряды обычно характеризуются малой длиной, типичным является проведение расчетов с рядами, содержащими несколько десятков членов. 

В значительной мере это обусловлено организацией деятельности национальных статистических служб. Макроэкономические показатели строятся, как правило, в месячном, квартальном и годовом выражениях. За отдельными исключениями (к числу которых относятся, например, временные ряды обменных курсов валют и других показателей финансовых рынков), макроэкономические показатели рассчитываются с шагом по времени не меньше месяца. Это обусловлено, в частности, технологическими соображениями, поскольку регистрация, сбор и первичная обработка данных требуют некоторого времени и значительных ресурсов. При этом методики построения одних и тех же показателей в месячном, квартальном и годовом выражениях зачастую несколько различаются. Как правило, чем выше частота временного ряда показателя, тем на меньший объем исходных данных он опирается (скажем, при построении показателей в годовом выражении часто бывает доступен больший объем более качественной исходной информации, чем при построении показателей в месячном выражении). Вместе с тем показатели более высокой частоты строятся и публикуются более оперативно и позволяют анализировать более краткосрочные тенденции, чем показатели меньшей частоты. Поэтому имеются основания строить и использовать показатели разной частоты. Годовые данные, как правило, наиболее точны, но не содержат информации о краткосрочных тенденциях, а соответствующие им временные ряды содержат наименьшее количество членов. Месячные данные зачастую менее точны, зато содержат информацию о краткосрочных тенденциях, соответствующие временные ряды имеют существенно большее количество членов, однако уровни таких рядов, как правило, несопоставимы между собой в силу наличия календарной и сезонной составляющих и большего масштаба нерегулярной составляющей. Удаление неинформативных составляющих динамики приводит к уменьшению числа степеней свободы, особенно заметному при использовании адаптивных методов, настраивающихся на эволюцию составляющих динамики. 

Проблема малой длины макроэкономических временных рядов особенно актуальна для российской переходной экономики. Отчасти это связано с тем, что переходный процесс сопровождался распадом союзного государства, вызвавшим утрату преемственности данных. Другая причина состоит в том, что плановая и рыночная экономики предъявляют разные требования к статистической информации и отличаются возможностями ее сбора. Это влечет необходимость перестройки системы показателей и методик их построения, что зачастую приводит к утрате преемственности экономических временных рядов. 

Требования к статистике меняются в том числе из-за контекста. После пандемии время публикации сдвинулось с 16.00 до 19.00, что могло повлиять на доступность этой информации для россиян.

Из-за санкций произошло закрытие таможенной статистики. Некоторая информация публикуется не настолько подробно – например, Банк России перестал публиковать отток капитала в разрезе стран.

Обычно методы обработки экономических временных рядов (скажем, методы декомпозиции рядов на составляющие динамики) позволяют получить гораздо лучшие результаты для внутренних членов временных рядов, достаточно удаленных от краев, тогда как по мере приближения к краям временного ряда качество результата существенно ухудшается (например, снижается точность идентификации составляющих динамики). Это позволяет говорить о краевых эффектах методов обработки экономических временных рядов, локализованных в некоторой окрестности краев ряда. Поэтому интерпретация результатов расчетов в области краевых эффектов требует особой осторожности. 

При обработке длинных временных рядов лишь небольшая часть их членов попадает в области краевых эффектов, поэтому аберрации методов, возникающие на краях временных рядов, не играют особой роли. При работе с короткими рядами ситуация существенно изменяется. Все члены короткого временного ряда можно рассматривать как близкие к его краям, что резко повышает важность адекватной обработки данных вблизи краев. Это предъявляет дополнительные требования к алгоритмам - они должны быть работоспособными вблизи краев временных рядов. Как правило, особый содержательный интерес представляют тенденции актуального конца (actual end) исследуемого временного ряда, т. е. выраженные членами ряда, непосредственно примыкающими к его правому краю, что усугубляет эту проблему.

## Высокочастотные данные {#sec-ts-highfreq}

Основное внимание экономистов продолжают привлекать традиционые макроэкономические ряды с частотой от месяца до года. Тем не менее в последнее время статистические ведомства, центральные банки и частные огранизацию разрабатывают и публикуют растущее число более оперативных индикаторов с еженедельной и ежедневной частотой публикации.

Среди наиболее наиболее зрелых оперативных макроэкономических показателей следует отметить недельные оценки роста потребительских цен Росстата и отчеты о производстве и ценах нефрепродуктов. Относительно новыми макроэкономическими данными являются индикатор данных о финансовых потоках и [новостной индекс деловых настроений](https://www.cbr.ru/vfs/ec_research/mb/news_index_week.xlsx) Банка Россиии. Среди госкорпораций, корпорация МСП стала публикует [данные по МСП](https://мсп.рф) в режиме реального времени на основе информации ФНС. Эти данные включают численность МСП по числу ИНН, выручку по регионам, средний чек, число ККТ.   

Средни индикаторов, разрабатываемых вне государственных ведомств, наиболее зрелую оперативную макроэкономическую статистику предлагает [СберИндекс](https://sberindex.ru/ru/dashboards?partition=6). Платформа СберИндекса дает возможность получить оперативные оценки по выручке для ряда секторов, динамике заработных плат, потреблению, которые основаны на внутренних данных Сбербанка: выплатам заработных плат, расходам по карточкам, данным чеков ОФД.  

Несмотря на рост доступности оперативных данных, работа с ними затруднена относительно низкой зрелостью методов сезонной и календарной коррекции и их нерегулярностью. В области коррекции недельных данных не сложилось прочных стандартов алгоритмов, но есть возможность выбрать из разнообразия экспериментальных методов, таких как [(Ginker, 2023)](https://cran.r-project.org/web/packages/boiwsa/boiwsa.pdf), [(Cleveland & Scott, 2007)](https://www.scb.se/contentassets/ca21efb41fee47d293bbee5bf7be7fb3/seasonal-adjustment-of-weekly-time-series-with-application-to-unemployment-insurance-claims-and-steel-production.pdf), [STL](https://otexts.com/fpp2/weekly.html) и [FB Prophet](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html).

## Резюме

* Главным объектом анализа экономической динамики являются временные ряды - упорядоченные по времени количественные индикаторы состояния экономической системы.

* Полезно различать моментные индикаторы, которые фиксируют значение на момент времени, и интервальные индикаторы, которые фиксируют значение за период времени. К первому типу относится уровень потребительских цен или валютный курс, ко второму - оборот розничной торговли за месяц или валовый внутренний продукт за квартал.

* Экономические временные ряды - это подмножество временных рядов, которое относится к оценкам состояния экономики. Динамику экономических индикатаров возможно разложить на трендовую, сезонную и календарную составляющие, однако эти компоненты могут быть в равной мере выражены.

* Макроэкономические временные ряды являются агрегированными индикаторами экономических временных рядов. Особенностью макроэкономических рядов является то, что они не являются непосредственными оценками характеристик объекта наблюдения, а строятся как суммарная, усредненная характеристика набора элементарных показателей по заданному алгоритму - методике построения индикатора. 

* Поскольку как методика оценки макроэкономических индикаторов на длинных периодах времени претерпевает значительные изменения, так и сам объект наблюдения - экономика - может значительно меняться, то сравнимость значение временного ряда друг с другом снижается по мере отдаления их друг от друга.